Move v1 package to schema package
influxdata/docs-v2 pull request #1670
Opened 2020-10-14 22:42 UTC by pierwill

Closes #1598.

- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2020-10-14 22:47 UTC, pierwill commented
![Screen Shot 2020-10-14 at 3 47 27 PM](https://user-images.githubusercontent.com/19642016/96053562-98d33980-0e34-11eb-9060-d936f671b4ab.png)

2020-10-15 11:57 UTC, sanderson commented
Be sure to add aliases for all the old locations.

2020-10-15 15:59 UTC, nathanielc requested changes
LGTM with exception of the `schema.databases` function, that remains in the `v1` package. And +1 to @sanderson 's comment all these functions are still available through the `v1` package for backwards compatibility, but we should probably update those to mention they are deprecated.

Do the docs use these functions in any examples? If so I would like to see those examples updated to use the new `schema` package instead.

2020-10-15 15:59 UTC, nathanielc commented on content/influxdb/v2.0/reference/flux/stdlib/schema/databases.md
> +title: schema.databases() function
The databases function remained in the v1 package.

2020-10-15 17:17 UTC, nathanielc commented on content/influxdb/v2.0/reference/flux/stdlib/schema/_index.md
> +Import the `influxdata/influxdb/schema` package:
We should remove the v1 language here, these schema functions apply equally to v1 or v2, hence why we have moved them.

2020-10-15 17:17 UTC, nathanielc commented on content/influxdb/v2.0/reference/flux/stdlib/influxdb-v1/_index.md
> +Functions from the `v1` package have moved to [`schema`](/influxdb/v2.0/reference/flux/stdlib/schema).
Not all the functions moved, just most. Specifically the json and databases functions remain in the v1 package.

2020-10-16 18:33 UTC, merged