Add timeShift() function to query docs
influxdata/docs-v2 pull request #1676
Opened 2020-10-15 22:41 UTC by pierwill

Closes https://github.com/influxdata/DAR/issues/123.

- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2020-10-15 23:08 UTC, abalone23 requested changes
`backware` should be `backward`

2020-10-16 16:48 UTC, abalone23 approved these changes

2020-10-16 20:34 UTC, kelseiv approved these changes

2020-10-16 20:34 UTC, kelseiv commented on content/influxdb/v2.0/query-data/flux/manipulate-timestamps.md
> +The [timeShift()](/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/timeshift/) function adds a fixed duration to time columns.
...adds the specified duration of time to each value in time columns ( `_start`, `_stop`, `_time`).

2020-10-16 20:38 UTC, merged