CQ migration guide
influxdata/docs-v2 pull request #1816
Opened 2020-11-11 23:43 UTC by sanderson

Closes #1803 

- [x] Tests pass (no build errors)
- [x] Rebased/mergeable

2020-11-11 23:49 UTC, pierwill approved these changes
A few nits. Looks good!

2020-11-11 23:49 UTC, pierwill commented on content/influxdb/v2.0/upgrade/v1-to-v2/migrate-cqs.md
> +title: Migrate continuous queries from InfluxDB 1.x to 2.0
Maybe "... to 2.0 tasks"?

2020-11-11 23:49 UTC, pierwill commented on content/influxdb/v2.0/upgrade/v1-to-v2/migrate-cqs.md
> +  Upgrade from InfluxDB 1.x to InfluxDB 2.0.
Needs revised—

2020-11-11 23:49 UTC, pierwill commented on content/influxdb/v2.0/upgrade/v1-to-v2/migrate-cqs.md
> +2. Copy and save all output continuous queries to your local machine.
Wording feels a bit off.

Maybe "Copy and save the displayed..."

2020-11-11 23:49 UTC, pierwill commented on content/influxdb/v2.0/upgrade/v1-to-v2/migrate-cqs.md
> +2. Remove the continuous query-specific statements and clauses (`CREATE CONTINUOUS QUERY`, `ON`, `BEGIN`, `END`)
Period at end of line.

2020-11-11 23:49 UTC, pierwill commented on content/influxdb/v2.0/upgrade/v1-to-v2/migrate-cqs.md
> +Use the `influx transpile` command to transpile your modified InfluxQL into Flux.
"transpile", or "convert"?

2020-11-11 23:49 UTC, pierwill commented on content/influxdb/v2.0/upgrade/v1-to-v2/migrate-cqs.md
> +The following resources are also available to help convert InfluxQL queries to Flux.
"...helpful when converting..."

2020-11-11 23:49 UTC, pierwill commented on content/influxdb/v2.0/upgrade/v1-to-v2/migrate-cqs.md
> +The following resources are also available to help convert InfluxQL queries to Flux.
(Just a thought.)

2020-11-11 23:49 UTC, timhallinflux requested changes

2020-11-11 23:49 UTC, timhallinflux commented on content/influxdb/v2.0/upgrade/v1-to-v2/migrate-cqs.md
> +To transpile a continuous query to Flux, you must modify the InfluxQL:
I don't think we should advertise the transpile command at all.
in fact, I feel like we should probably drop it.  It isn't being developed.

2020-11-11 23:49 UTC, timhallinflux commented on content/influxdb/v2.0/upgrade/v1-to-v2/migrate-cqs.md
> +### influx transpile command
remove....I think.

2020-11-13 17:09 UTC, merged

2020-11-13 17:21 UTC, kelseiv commented on content/influxdb/v2.0/upgrade/v1-to-v2/migrate-cqs.md
> +from(bucket: "my-db/")
forward slash intentional?

2020-11-13 17:21 UTC, kelseiv commented on content/influxdb/v2.0/upgrade/v1-to-v2/migrate-cqs.md
> +    bucket: "my-db/downsampled-daily"
downsample-daily?

2020-11-13 17:21 UTC, kelseiv commented on content/influxdb/v2.0/upgrade/v1-to-v2/migrate-cqs.md
> +    bucket: "my-db/downsampled-daily"
Perhaps explicitly point out differences that may make folks wonder? Like why there isn't "average-example-measurement" in Flux query, and example of how time "range" was set for CQs.