Use Kapacitor and Chronograf with InfluxDB Cloud and OSS 2.0
influxdata/docs-v2 pull request #1827
Opened 2020-11-13 22:16 UTC by sanderson

Closes #1804

- [x] Tests pass (no build errors)
- [x] Rebased/mergeable

2020-11-14 00:00 UTC, timhallinflux requested changes

2020-11-14 00:00 UTC, timhallinflux commented on content/influxdb/v2.0/tools/kapacitor.md
> +InfluxDB Cloud and InfluxDB OSS 2.0 to not have subscriptions APIs.
to -> do

2020-11-14 00:00 UTC, timhallinflux commented on content/influxdb/v2.0/tools/kapacitor.md
> +InfluxDB Cloud and OSS 2.0 do not have subsription APIs and do not support Kapacitor stream tasks directly.
subscription (sp)

2020-11-14 00:01 UTC, timhallinflux commented on content/influxdb/v2.0/tools/kapacitor.md
> +[Kapacitor](/{{< latest "kapacitor" >}}/) is a data processing framework that makes
But something about the batch tasks take advantage of the read and write 1.x compatibility APIs.  (read for the influxql query and write for the write back)....

2020-11-16 16:29 UTC, sanderson commented on content/influxdb/v2.0/tools/chronograf.md
> +Use [Chronograf](/{{< latest "chronograf" >}}/) to visualize data from **InfluxDB Cloud** and **InfluxDB OSS 2.0**.
Updated the intro and created a new section:

```md
[Chronograf](/{{< latest "chronograf" >}}/) is a data visualization and dashboarding
tool designed to visualize data in InfluxDB 1.x. It is part of the [TICKstatck](/platform/)
that provides an InfluxQL data explorer, Kapacitor integrations, and more.
Continue to use Chronograf with **InfluxDB Cloud** and **InfluxDB OSS 2.0** and the
[1.x compatibility API](/influxdb/v2.0/reference/api/influxdb-1x/).

{{% warn %}}
### Important notes

#### No administrative functionality
Chronograf cannot be used for administrative tasks in InfluxDB Cloud and InfluxDB OSS 2.0.
For example:

- defining databases
- modifying retention policies
- adding users
- etc.

You must migrate administrative tasks to the native InfluxDB Cloud or InfluxDB OSS 2.0
user interface (UI).

#### Limited InfluxQL support
InfluxDB Cloud and InfluxDB OSS 2.0 support InfluxQL **read-only** queries.
For more information, see [InfluxQL support](/influxdb/v2.0/query-data/influxql/#influxql-support),
{{% /warn %}}
```

2020-11-20 21:59 UTC, timhallinflux commented on content/influxdb/v2.0/tools/chronograf.md
> +Use [Chronograf](/{{< latest "chronograf" >}}/) to visualize data from **InfluxDB Cloud** and **InfluxDB OSS 2.0**.
You must perform administrative tasks via the native InfluxDB Cloud or InfluxDB OSS 2.0
user interface (UI) or CLI tooling.

2020-11-20 21:59 UTC, timhallinflux commented on content/influxdb/v2.0/tools/chronograf.md
> +Use [Chronograf](/{{< latest "chronograf" >}}/) to visualize data from **InfluxDB Cloud** and **InfluxDB OSS 2.0**.
link to the CLI docs ^

2020-11-20 23:46 UTC, kelseiv commented on content/influxdb/v2.0/tools/chronograf.md
> +   see [Use Kapacitor with InfluxDB](/influxdb/v2.0/tools/kapacitor/)._
5. To configure..., click.... Otherwise, click...

2020-11-20 23:46 UTC, kelseiv commented on content/influxdb/v2.0/tools/chronograf.md
> +   _For more information about using Kapacitor with InfluxDB Cloud or InfluxDB OSS 2.0,
For information...

2020-11-20 23:46 UTC, kelseiv commented on content/influxdb/v2.0/tools/kapacitor.md
> +section(s) of your Kapacitor configuration file:
how to open Kapacitor config file?

2020-11-20 23:46 UTC, kelseiv commented on content/influxdb/v2.0/tools/kapacitor.md
> +Ensure the provided InfluxDB authentication token has the necessary read and write permissions.
To ensure...., link to how folks can verify permissions

2020-11-20 23:46 UTC, kelseiv commented on content/influxdb/v2.0/tools/kapacitor.md
> +Set the `[[influxdb]].disable-subscriptions`to `false` to disable InfluxDB subscriptions.
Set...to `true`?

2020-11-20 23:46 UTC, kelseiv commented on content/influxdb/v2.0/tools/kapacitor.md
> +To use Kapacitor stream tasks, write data directly to Kapacitor using the [Kapcitior `/write` API](/{{< latest "kapacitor" >}}/working/api/#writing-data).
[Kapacitor `write`...

2020-11-20 23:46 UTC, kelseiv commented on content/influxdb/v2.0/tools/chronograf.md
> +- definine databases
initial cap

2020-11-23 17:36 UTC, merged