etcd updates
influxdata/docs-v2 pull request #1846
Opened 2020-11-17 19:52 UTC by noramullen1

Addresses #1414

2020-11-17 19:58 UTC, timhallinflux requested changes
if we have multiple entries for a particular param, multiple command line flags are supported.
unless you are using environment variables....in which case the comma separated list is the way.

Need to confirm for each of the items listed in the underlying issue are covered (either in this PR or another?).

2020-11-17 19:58 UTC, timhallinflux commented on content/chronograf/v1.8/administration/create-high-availability.md
>  ## Start Chronograf
super clear!

2020-11-17 19:58 UTC, timhallinflux commented on content/chronograf/v1.8/tools/chronograf-cli/_index.md
> +| `-o`, `--github-organization`  | Restricts authorization to users from comma-separated list of specified Github organizations. Optional. | `$GH_ORGS`          |
I don't think this matches what the underlying issue outlines.  These are flags... and when using flags it implies having multiple flags.  

When using environment variables --> then the comma-separated list works.

2020-11-17 19:58 UTC, timhallinflux commented on content/chronograf/v1.8/tools/chronograf-cli/_index.md
> +| `--google-domains`       | Restricts authorization to users from comma-separated list of specified Google email domains. Optional. | `$GOOGLE_DOMAINS`       |
I don't think this matches what the underlying issue outlines.  These are flags... and when using flags it implies having multiple flags.  

When using environment variables --> then the comma-separated list works.

2020-11-17 19:58 UTC, timhallinflux commented on content/chronograf/v1.8/tools/chronograf-cli/_index.md
> +| `--auth0-organizations` | Restricts authorization to  users from comma-separated list of specified Auth0 organizations. Optional. Organizations are set using an organization key in the user’s `app_
I don't think this matches what the underlying issue outlines.  These are flags... and when using flags it implies having multiple flags.  

When using environment variables --> then the comma-separated list works.

2020-11-17 19:58 UTC, timhallinflux commented on content/chronograf/v1.8/tools/chronograf-cli/_index.md
> +| `--heroku-organization` | Restricts authorization to  users from comma-separated list of specified Heroku orgnizations. Optional. | `$HEROKU_ORGS`      |
I don't think this matches what the underlying issue outlines.  These are flags... and when using flags it implies having multiple flags.  

When using environment variables --> then the comma-separated list works.

2020-11-17 22:38 UTC, timhallinflux requested changes
where do we specify how to handle the comma separated list when using an Env Var?

I think we should add this content here: https://docs.influxdata.com/chronograf/v1.8/administration/config-options/

under each env var where it applies?

We've got some of this already....but the language is inconsistent: ex -> Lists are comma-separated and are only available when using environment variables.

Instead of saying "lists" -- I would suggest something like:  multiple <thing> can be specified using a comma-separated list. Then show an example.

2020-11-20 20:01 UTC, timhallinflux requested changes
looks great.  Seems like there is one example still missing:
`--heroku-organization=`

I think we hit that one and this is ready to go!

2020-11-20 21:54 UTC, timhallinflux approved these changes
gtg!

2020-11-20 22:28 UTC, kelseiv approved these changes

2020-11-20 22:38 UTC, merged