docs: added bigpanda.md event handler documentation
influxdata/docs-v2 pull request #1948
Opened 2020-12-07 10:09 UTC by rhajek

BigPanda event handler documentation.

_Describe your proposed changes here._

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2020-12-07 19:00 UTC, sanderson requested changes
Thanks for this @rhajek. Just a few changes needed.

2020-12-07 19:00 UTC, sanderson commented on content/kapacitor/v1.5/event_handlers/bigpanda.md
> +[BigPanda Alert REST API](https://docs.bigpanda.io/reference#alerts) for more information.
- All EventData tags are ~also~ appended ~into~ **to the** BigPanda alert as **Additional attributes**

2020-12-08 20:11 UTC, docmerlin commented
@sanderson go ahead and target master with this.  This isn't something we have to backport, so we use the easy workflow of treating master as tip.

2020-12-09 20:10 UTC, docmerlin commented
On, My end, I don't see anything still glaring. Once Sanderson is happy, I'll go ahead and merge.

2020-12-09 20:23 UTC, sanderson approved these changes
Thanks @rhajek !

2020-12-09 20:23 UTC, merged