Update auth steps for InfluxQL against Influx2.0
influxdata/docs-v2 pull request #2029
Opened 2021-01-05 19:20 UTC by BojanOro

Addresses https://github.com/influxdata/docs-v2/issues/1942

Closes #1942

The current documentation is misleading with respect to using Grafana with InfluxQL with Influx2.0. This change seeks to correct this.

You do not need basic authentication, you need only add a custom HTTP header with your token. 

See:
https://github.com/influxdata/docs-v2/issues/1942
https://github.com/grafana/grafana/issues/29372

- [x] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Tests pass (no build errors)
- [x] Rebased/mergeable

2021-01-19 18:06 UTC, sanderson requested changes
Thanks for this @BojanOro. Sorry for the slow review. Just some minor changes requested.

2021-01-19 18:06 UTC, sanderson commented on content/influxdb/v2.0/tools/grafana.md
> +    - **Value**: In the form of "Token <your InfluxDB [authentication token](/influxdb/v2.0/security/tokens/)>"
- Combine `2.` and `3.` into a single line item
- Format "Authorization" as inline code
- With the head value, outline the pattern and provide an example:

~~~md
2. Under **Custom HTTP Headers**, select **Add Header**.
   Provide your InfluxDB authentication credentials:

    - **Header**: `Authorization`
    - **Value**: use the `Token` schema and provide your [InfluxDB authentication token](/influxdb/v2.0/security/tokens/) (for example: `Token y0uR5uP3rSecr3tT0k3n`)
~~~

2021-02-05 01:55 UTC, jmmk commented
It seems the credentials in bullet 4 may also be unnecessary:

<img width="835" alt="image" src="https://user-images.githubusercontent.com/1122242/106978727-d3861800-672a-11eb-96ce-f3fa58a02476.png">

2021-02-25 15:46 UTC, diamondsw commented
Priority indeed since Influx just updated all of our Docker containers to 2.0 without warning. Cue mass grafana breakage.

2021-02-25 16:27 UTC, sanderson commented
@diamondsw Sorry for lack of content. I'm working on updating the Grafana docs today and will ping you when they're live.

2021-02-25 16:33 UTC, BojanOro commented
Apologies for the huge delay, this got dropped and I forgot entirely about this until I started getting emails about comments 😬 . Let me know if the docs make sense now!

2021-02-25 16:52 UTC, sanderson approved these changes

2021-02-25 16:52 UTC, merged