Document using InfluxDB 2 as a systemd service
influxdata/docs-v2 pull request #2096
Opened 2021-01-25 21:58 UTC by pierwill

- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2021-01-25 22:37 UTC, sanderson requested changes
Just some nits

2021-01-25 22:37 UTC, sanderson commented on content/influxdb/v2.0/get-started.md
> +### Installing as a service (with systemd)
```suggestion
### Install InfluxDB as a service with systemd
```

2021-01-25 22:37 UTC, sanderson commented on content/influxdb/v2.0/get-started.md
> +The following instructions have been tested on Ubuntu, and should work similarly on other operating systems.
```suggestion
{{% note %}}
The following instructions have been tested on Ubuntu, and should work similarly on other operating systems.
{{% /note %}}
```

2021-01-25 22:37 UTC, sanderson commented on content/influxdb/v2.0/get-started.md
> +1. Download the Ubuntu & Debian `.deb` file from the [downloads page](https://portal.influxdata.com/downloads/).
```suggestion
1. Download the appropriate Ubuntu & Debian `.deb` file from the [InfluxData downloads page](https://portal.influxdata.com/downloads/).
```

2021-01-25 22:37 UTC, sanderson commented on content/influxdb/v2.0/get-started.md
> +   (The actual file name will contain version number and architecture information such as `amd64`.)
```suggestion
   _Use the actual filename of the downloaded InfluxDB `.deb` package._
```

2021-01-25 22:37 UTC, sanderson commented on content/influxdb/v2.0/get-started.md
> +3. Start the service by running
```suggestion
3. Start the InfluxDB service:
```

2021-01-25 22:37 UTC, sanderson commented on content/influxdb/v2.0/get-started.md
> +   This file means that InfluxDB will start as a background service at boot.
```suggestion
   The installation process creates a service file at `/lib/systemd/services/influxdb.service`,
   which starts InfluxDB start as a background service on boot.
```

2021-01-25 22:37 UTC, sanderson commented on content/influxdb/v2.0/get-started.md
> +4. Restart your system, and verify that the service is running correctly:
```suggestion
4. Restart your system and verify that the service is running correctly:
```

2021-01-26 00:18 UTC, kelseiv commented on content/influxdb/v2.0/get-started.md
> +   which starts InfluxDB start as a background service on boot.
```suggestion
   Installing InfluxDB creates a service file at `/lib/systemd/services/influxdb.service` to start InfluxDB as a background service on startup.
```

2021-01-26 18:47 UTC, pierwill commented on content/influxdb/v2.0/get-started.md
> +The following instructions have been tested on Ubuntu, and should work similarly on other operating systems.
If they've already downloaded the binaries, the `.deb` packages are still the best way to go since they will include the systemd `.service` file.

2021-01-26 18:47 UTC, pierwill commented on content/influxdb/v2.0/get-started.md
> +The following instructions have been tested on Ubuntu, and should work similarly on other operating systems.
For other Linux systems, I think we'll want to wait until we can test them out to document them.

2021-01-26 20:45 UTC, kelseiv commented on content/influxdb/v2.0/get-started.md
> +The following instructions have been tested on Ubuntu, and should work similarly on other operating systems.
> other Linux operating systems?

So folks can run InfluxDb as a service on OS other than Linux variants

2021-01-26 20:48 UTC, pierwill commented on content/influxdb/v2.0/get-started.md
> +The following instructions have been tested on Ubuntu, and should work similarly on other operating systems.
I'm not sure how Mac and Windows handle services.

2021-01-26 20:48 UTC, pierwill commented on content/influxdb/v2.0/get-started.md
> +The following instructions have been tested on Ubuntu, and should work similarly on other operating systems.
The docs in this PR work for Debian and Ubuntu. I haven't been able to confirm any others work properly yet.

2021-01-26 20:59 UTC, kelseiv commented on content/influxdb/v2.0/get-started.md
> +The following instructions have been tested on Ubuntu, and should work similarly on other operating systems.
gotcha on that part...was curious if it'd be preferable to clarify they should work similarly on other Linux OS, but imagine services in general would work differently on moc/windows....just want to be sure that we're confident saying they should work similarly on other systems given we haven't tested

2021-01-26 21:00 UTC, pierwill commented on content/influxdb/v2.0/get-started.md
> +The following instructions have been tested on Ubuntu, and should work similarly on other operating systems.
Ah! Should change "other operating systems" to "other Linux distributions"! Thanks! 🙏

2021-01-26 22:55 UTC, kelseiv approved these changes

2021-01-26 22:59 UTC, merged