Chronograf 1.8.10
influxdata/docs-v2 pull request #2142
Opened 2021-02-04 20:36 UTC by kelseiv

Closes https://github.com/influxdata/docs-v2/issues/2141

2021-02-08 22:19 UTC, russorat approved these changes
LGTM

2021-02-09 00:03 UTC, timhallinflux requested changes
Is there a section of the docs that describes the meta query templates?  because we've added DROP SERIES, DELETE and DROP MEASUREMENT.  I can't seem to find a description of these in the Data Explorer walk thru.

2021-02-10 03:00 UTC, kelseiv commented
> Is there a section of the docs that describes the meta query templates? because we've added DROP SERIES, DELETE and DROP MEASUREMENT. I can't seem to find a description of these in the Data Explorer walk thru.

@timhallinflux, we mention "Metaquery Templates" in step 4 of [Explore data with InfluxQL](https://docs.influxdata.com/chronograf/v1.8/guides/querying-data/#explore-data-with-influxql)...however, it appears something was inadvertently deleted. Created [an issue](https://github.com/influxdata/docs-v2/issues/2164) to resolve this and related docs issues.

2021-02-10 18:43 UTC, timhallinflux commented on content/chronograf/v1.8/about_the_project/release-notes-changelog.md
> +- Upgrade to Axios 0.21.1.
move to Bug Fix/maintenance?

2021-02-10 22:44 UTC, merged