Updated the UI references
influxdata/docs-v2 pull request #2234
Opened 2021-03-03 15:29 UTC by mprintz

Added the new UI pictures and references to the button locations. Also added more info on the retention policy.

Closes #

Added the new UI pictures and references to the button locations. Also added more info on the retention policy.

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2021-03-03 15:30 UTC, mprintz commented
My pictures pasted too large in this request. Sorry. The brackets are showing too I think. Let me know if you want better pictures or if you have a way to resize them correctly.

2021-03-03 17:29 UTC, sanderson requested changes
- The menu references and nav icos follow a convention we've established to address both the collapsed and expanded states of the left nav. 
- Images should be added directly to the repo rather than served from Github. In this case, I don't think the images are necessary and have suggested changes to help clarify the instructions.

2021-03-03 17:29 UTC, sanderson commented on content/influxdb/cloud/organizations/buckets/update-bucket.md
> +    {{![image](https://user-images.githubusercontent.com/9125473/109828439-3e2f5400-7c02-11eb-8fb3-f0e8b5f34a3a.png)}}
This is a convention we've established to address both the collapsed and expanded states of the left nav. These should not be changed.

2021-03-03 17:29 UTC, sanderson commented on content/influxdb/cloud/organizations/buckets/update-bucket.md
> +2. Click **Settings** to the right of the current name of the bucket that you want to rename.
```suggestion
2. Click **Settings** to the right of the bucket you want to rename.
```

2021-03-03 17:29 UTC, sanderson commented on content/influxdb/cloud/organizations/buckets/update-bucket.md
> +
This is a convention we've established to address both the collapsed and expanded states of the left nav. These should not be changed.

2021-03-03 17:29 UTC, sanderson commented on content/influxdb/cloud/organizations/buckets/update-bucket.md
> +    {{![image](https://user-images.githubusercontent.com/9125473/109828711-7fbfff00-7c02-11eb-94fa-9acc07a65296.png)}}
```suggestion
3. In the window that appears, under **Delete data**, select a retention period:

    - **Never**: data in the bucket is retained indefinitely.
    - **Older Than**: select a predefined retention period from the dropdown menu.
    
    {{% note %}}
Use the [`influx bucket update` command](#update-a-buckets-retention-policy) to set a custom retention policy.
    {{% /note %}}
```

2021-03-04 03:04 UTC, mprintz commented
Thanks @sanderson !

2021-03-04 03:05 UTC, mprintz reviewed
Looks good. Thanks @sanderson

2021-03-04 18:02 UTC, sanderson commented on content/influxdb/cloud/organizations/buckets/update-bucket.md
> +
```suggestion
1. In the navigation menu on the left, select **Data (Load Data)** > **Buckets**.

    {{< nav-icon "data" >}}
    
```

2021-03-04 18:02 UTC, sanderson commented on content/influxdb/cloud/organizations/buckets/update-bucket.md
> +    {{![image](https://user-images.githubusercontent.com/9125473/109828439-3e2f5400-7c02-11eb-8fb3-f0e8b5f34a3a.png)}}
```suggestion
    {{< nav-icon "data" >}}
```

2021-03-04 18:04 UTC, sanderson approved these changes

2021-03-04 18:05 UTC, merged