Add new content on string interpolation from SPEC.md
influxdata/docs-v2 pull request #2326
Opened 2021-03-22 14:22 UTC by pierwill

Closes #2314

- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2021-03-22 15:22 UTC, sanderson requested changes
A few things:

- This change is bound to a Flux release that hasn't happened yet. This shouldn't be merged into `master`. We need to create a `flux-0.109` branch and use that as the base branch for these changes.
- These changes are only part of a much broader set of changes that need to take place:
    - Updating this doc: https://docs.influxdata.com/influxdb/v2.0/reference/flux/language/string-interpolation/
    - Updating all the string interpolation examples through the docs that use the string function to convert interpolated non-string values to strings: `"${string(v: ... )}"`.

  The challenge here is that this version of Flux will not be immediately available in each version of InfluxDB. It will roll out to Cloud, and hopefully be part of InfluxDB 2.0.5. Not sure exactly how to handle this. My first thought is to leave the `string()` examples in there since they're still valid and change them once the new version of Flux is widely distributed.

2021-03-22 15:22 UTC, sanderson commented on content/influxdb/v2.0/reference/flux/language/string-interpolation.md
> +String interpolation expressions must satisfy the Stringable constraint.
- Add the "Stringable" constraint to this doc: /influxdb/v2.0/reference/flux/language/types/#type-constraints
- Link "Stringable constraint" to the new section

2021-03-22 15:22 UTC, sanderson commented on content/influxdb/v2.0/reference/flux/language/string-interpolation.md
> +    "the answer is ${t0}" // the answer is 2016-06-13T17:43:50.1004002Z
~~~suggestion
##### Arbitrary expression interpolation example:
```js
n = duration(v: "1m") 
"the answer is ${n}"
// the answer is 1m

t0 = time(v: "2016-06-13T17:43:50.1004002Z")
"the answer is ${t0}"
// the answer is 2016-06-13T17:43:50.1004002Z
```
~~~

2021-03-22 15:40 UTC, pierwill commented
Thanks, @sanderson. I've created the `flux-0.109` branch.

2021-03-25 22:38 UTC, sanderson approved these changes

2021-03-25 22:39 UTC, sanderson commented
Merging this now without updating the string interpolation examples. There's a defect in the current string interpolation implementation that will be fixed in a future release. Once it's released, we'll go through and update all the examples.

2021-03-25 22:39 UTC, merged