Kapacitor 1.5.9 release notes
influxdata/docs-v2 pull request #2372
Opened 2021-03-30 23:51 UTC by kelseiv

Closes https://github.com/influxdata/docs-v2/issues/2331

2021-03-30 23:57 UTC, kelseiv commented on content/kapacitor/v1.5/about_the_project/releasenotes-changelog.md
> +## v1.5.9 [TBD]
Do we need to add any of the content that we pulled for the 1.5.8 release back into the 1.5./9 release?

2021-03-30 23:57 UTC, kelseiv commented on content/kapacitor/v1.5/about_the_project/releasenotes-changelog.md
> +- Add default color theme to teams alerts, thanks @NoamShaish!
Are these Microsoft Teams alerts...or something else?

2021-03-31 19:18 UTC, docmerlin commented on content/kapacitor/v1.5/about_the_project/releasenotes-changelog.md
> +- Add default color theme to teams alerts, thanks @NoamShaish!
@kelseiv  Yes, microsoft teams alerts.

2021-04-01 21:02 UTC, timhallinflux approved these changes

2021-04-01 22:41 UTC, docmerlin requested changes

2021-04-01 22:41 UTC, docmerlin commented on content/kapacitor/v1.5/about_the_project/releasenotes-changelog.md
> +- Remove support for `darwin/386` builds (Go no longer supports), and add support for `darwin/arm64` builds.
We don't support darwin/arm64

2021-04-01 22:45 UTC, docmerlin approved these changes

2021-04-02 01:33 UTC, merged