Move "Hardware sizing guidelines" to Reference section
influxdata/docs-v2 pull request #2454
Opened 2021-04-28 20:27 UTC by pierwill

Seems to me this makes more sense here.

- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2021-04-28 20:28 UTC, pierwill commented
### TODO
- [ ] update links

2021-04-28 20:29 UTC, sanderson commented on content/enterprise_influxdb/v1.9/guides/hardware_sizing.md
> +  enterprise_influxdb_1_9_ref
This still needs a weight.

2021-04-28 20:38 UTC, sanderson requested changes
Where you just changed the menu key, you don't actually have to update any links. The filepaths stay the same. For the 1.x docs, I think this is the way to go.

2021-04-28 20:51 UTC, pierwill commented
As in, links to `/enterprise_influxdb/v1.9/guides/hardware_sizing/` would be redirected to `/enterprise_influxdb/v1.9/reference/hardware_sizing/`? Still, it's a bit confusing to future editors if we don't update the links, IMO.

2021-04-28 20:52 UTC, pierwill commented
Ah, I see. I think it's best to move the file as well.

2021-04-28 21:04 UTC, sanderson requested changes

2021-04-28 21:04 UTC, sanderson commented on content/enterprise_influxdb/v1.9/reference/hardware_sizing.md
>      weight: 40
```suggestion
menu: enterprise_influxdb_1_9_ref
weight: 40
alias:
  - /enterprise_influxdb/v1.9/guides/hardware_sizing/
```

2021-04-28 21:04 UTC, sanderson commented on content/enterprise_influxdb/v1.9/reference/hardware_sizing.md
>  menu:
If you accept my suggestion below, remove this line.

2021-04-29 03:06 UTC, sanderson approved these changes

2021-04-29 03:37 UTC, merged