draft-in-progress
influxdata/docs-v2 pull request #2525
Opened 2021-05-12 15:42 UTC by kelseiv

Closes https://github.com/influxdata/docs-v2/issues/2287

Incorporate content from Chris. WIP.

@sanderson, I figured dropping this content on the "Create histograms with Flux" page was the best fit. Chris referred to the `histogramquantile()` function specifically, so perhaps a link there as well? Lmk your thoughts-thanks!

2021-05-13 19:05 UTC, sanderson requested changes

2021-05-13 19:05 UTC, sanderson commented on content/influxdb/v2.0/query-data/flux/histograms.md
> +histos =
```suggestion
histograms =
```

2021-05-13 19:05 UTC, sanderson commented on content/influxdb/v2.0/query-data/flux/histograms.md
> +  histos |> doQuantile(q:  0.5)
```suggestion
  histograms |> doQuantile(q:  0.95),
  histograms |> doQuantile(q:  0.5)
```

2021-05-13 19:05 UTC, sanderson commented on content/influxdb/v2.0/query-data/flux/histograms.md
> +The tables flowing into the call to `histogramQuantile` should look similar to this. Note, that rows are sorted by `le` to be clear that the counts increase for larger upper bounds):
```suggestion
The tables piped-forward into `histogramQuantile()` should look similar to those returned by the `histograms` variable in the example above. Note, that rows are sorted by `le` to be clear that the counts increase for larger upper bounds.
```

2021-05-13 20:49 UTC, sanderson approved these changes

2021-05-17 20:30 UTC, wolffcm approved these changes
@kelseiv @sanderson This looks great!

The `histogram()` function will create histogram data from a metric, similar to the data produced by scraping a prometheus endpoint. As such users can use the guide in this PR to convert it to quantiles with `histogramQuantile()` as well.

I already see a link to this page in the `histogram()` function page in the `Related` section, so think that's good enough.

Thanks for taking the time to fix up my prose!

2021-05-17 20:49 UTC, merged