Add example for creating a task via API
influxdata/docs-v2 pull request #2556
Opened 2021-05-17 20:38 UTC by pierwill

Also, use "duplicate-oss" shortcode for "Create a task".

Closes #2540

- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2021-05-17 22:41 UTC, sanderson requested changes
Some minor suggestions.

2021-05-17 22:41 UTC, sanderson commented on content/influxdb/v2.0/process-data/manage-tasks/create-task.md
> +
We should list what they need to provide in the API call. For example:

```suggestion
Provide the following in your API request:

- `/api/v2/tasks` InfluxDB API endpoint
- **POST** request method

##### Request headers
- **Content-Type**: application/json
- **Authorization**: Token _YOURINFLUXDBTOKEN_**

##### Request body
JSON object with the following fields:

- **flux** : raw Flux task string
- **orgID**: your [InfluxDB organization ID](/influxdb/v2.0/organizations/view-orgs/#view-your-organization-id)
- **status**: task status ("active" or "inactive")
- **description**: task description
```

2021-05-17 22:41 UTC, sanderson commented on content/influxdb/v2.0/process-data/manage-tasks/create-task.md
> +```
- Specify syntax highlighting on the code block.
- For simplicity, we can probably leave out the `--location` flag. This just tells the request to follow redirects.
- Totally nit-picky, so feel free to ignore, but I like to indent lines after an escaped newline in commands to show that it's still part of the same command:
- 
~~~suggestion
```sh
curl --request POST 'https://us-west-2-1.aws.cloud2.influxdata.com/api/v2/tasks' \
  --header 'Content-Type: application/json' \
  --header 'Authorization: Token <YOURTOKEN>' \
  --data-raw '{
    "flux": "option task = {name: \"CPU Total 1 Hour New\", every: 1h}\n\nfrom(bucket: \"telegraf\")\n\t|> range(start: -1h)\n\t|> filter(fn: (r) =>\n\t\t(r._measurement == \"cpu\"))\n\t|> filter(fn: (r) =>\n\t\t(r._field == \"usage_system\"))\n\t|> filter(fn: (r) =>\n\t\t(r.cpu == \"cpu-total\"))\n\t|> aggregateWindow(every: 1h, fn: max)\n\t|> to(bucket: \"cpu_usage_user_total_1h\", org: \"russ+cloud2'\''s organization\")",
    "orgID": "<YOURORGID>",
    "status": "active",
    "description": "This task downsamples CPU data every hour"
}'
```
~~~

2021-05-18 14:31 UTC, sanderson approved these changes
One minor update and it looks great. Ship it!

![https://media.giphy.com/media/cEYFeE4wJ6jdDVBiiIM/giphy-downsized.gif](https://media.giphy.com/media/cEYFeE4wJ6jdDVBiiIM/giphy-downsized.gif)

2021-05-18 14:31 UTC, sanderson commented on content/influxdb/v2.0/process-data/manage-tasks/create-task.md
> +```sh
I should've left a new line here. This may not render correctly without it.

~~~suggestion
- **description**: task description

```sh
~~~

2021-05-18 14:51 UTC, merged

2021-05-18 18:06 UTC, russorat commented on content/influxdb/v2.0/process-data/manage-tasks/create-task.md
> +    "flux": "option task = {name: \"CPU Total 1 Hour New\", every: 1h}\n\nfrom(bucket: \"telegraf\")\n\t|> range(start: -1h)\n\t|> filter(fn: (r) =>\n\t\t(r._measurement == \"cpu\"))\n\t|> filter(fn:
can we remove my org name from the official example?