Add missing MQTT option parameter
influxdata/docs-v2 pull request #2591
Opened 2021-05-25 18:33 UTC by pierwill

Closes #2538

- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2021-05-25 20:53 UTC, sanderson reviewed
I might be wrong, but I know with other Kapacitor boolean params, the value has to be all caps (`TRUE`).

@docmerlin, can you confirm?

2021-05-25 21:56 UTC, pierwill commented on content/kapacitor/v1.5/event_handlers/mqtt.md
> +    .retained(true)
```suggestion
    .retained(TRUE)
```

2021-05-25 21:56 UTC, pierwill commented
Thanks Scott. That was the original suggestion in the issue. Updated.

2021-05-25 22:58 UTC, sanderson requested changes
One last quick change and it should be good to go. You should also include the `retained` param in the handler file example beginning on line 188:

```yaml
# ...
options: 
  broker-name: 'alerts-broker' 
  topic: 'alerts' 
  qos: 2
  retained: true
```

2021-05-26 16:01 UTC, sanderson approved these changes
LGTM

2021-05-26 16:04 UTC, merged