Kapacitor 1.6.0 jstirnaman
influxdata/docs-v2 pull request #2684
Opened 2021-06-08 21:21 UTC by jstirnaman

Closes #

_Describe your proposed changes here._

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2021-06-08 21:23 UTC, jstirnaman commented
@sanderson I haven't been able to test this on 1.6.

2021-06-09 04:34 UTC, sanderson requested changes
Some suggestions.

2021-06-09 04:34 UTC, sanderson commented on content/kapacitor/v1.6/working/api.md
> +| permissions | A list of valid user permission strings. Any of `none`, `api`, `config_api`, `write_points`, `all`. |
```suggestion
Define a user as a JSON object with the following properties:

| Property    | Description                                                                                |
| :---------- | :----------------------------------------------------------------------------------------- |
| name        | Username                                                                                   |
| password    | Password                                                                                   |
| type        | User type  (`user` or `admin`, _see [User](/influxdb/v1.6/concepts/glossary/#user)_)       |
| permissions | List of valid user permission strings (`none`, `api`, `config_api`, `write_points`, `all`) 
```

2021-06-09 04:34 UTC, sanderson commented on content/kapacitor/v1.6/working/api.md
> +```
```suggestion
```sh
curl --XPOST 'http://localhost:9092/kapacitor/v1/users' \
  --data '{
    "name": "stan",
    "password": "pass",
    "type":"normal",
    "permissions": ["config_api"]
}'
```
```

2021-06-09 04:34 UTC, sanderson commented on content/kapacitor/v1.6/working/api.md
> +| permissions | A list of valid user permission strings. Any of `none`, `api`, `config_api`, `write_points`, `all`. |
```suggestion
| Property    | Purpose                                                                                    |
| :---------- | :----------------------------------------------------------------------------------------- |
| password    | Password                                                                                   |
| type        | User type (`user` or `admin`, _see [User](/influxdb/v1.6/concepts/glossary/#user)_)        |
| permissions | List of valid user permission strings (`none`, `api`, `config_api`, `write_points`, `all`) |
```

2021-06-09 04:34 UTC, sanderson commented on content/kapacitor/v1.6/working/api.md
> +To update a user, PATCH to the `/kapacitor/v1/users/<name>` endpoint.
```suggestion
To update a user, use the PATCH request method with the `/kapacitor/v1/users/<name>` endpoint.
```

2021-06-09 04:34 UTC, sanderson commented on content/kapacitor/v1.6/working/api.md
> +To create a user, POST to the `/kapacitor/v1/users` endpoint.
```suggestion
To create a user, use the POST request method with the `/kapacitor/v1/users` endpoint.
```

2021-06-09 04:34 UTC, sanderson commented on content/kapacitor/v1.6/working/api.md
> +To list users, send a GET request to the `/kapacitor/v1/users` endpoint.
```suggestion
To list users, use the GET request method with the `/kapacitor/v1/users` endpoint.
```

2021-06-09 04:34 UTC, sanderson commented on content/kapacitor/v1.6/working/api.md
> +To delete a user, send a DELETE request to the `/kapacitor/v1/users/<name>` endpoint.
```suggestion
To delete a user, use the DELETE request method with the `/kapacitor/v1/users/<name>` endpoint.
```

2021-06-09 14:00 UTC, jstirnaman commented on content/kapacitor/v1.6/working/api.md
> +| type        | User type  (`user` or `admin`, _see [User](/influxdb/v1.6/concepts/glossary/#user)_)       |
```suggestion
| type        | User type  (`normal` or `admin`, _see [User](/influxdb/v1.6/concepts/glossary/#user)_)       |
```

2021-06-09 14:00 UTC, jstirnaman commented on content/kapacitor/v1.6/working/api.md
> +| type        | User type (`user` or `admin`, _see [User](/influxdb/v1.6/concepts/glossary/#user)_)        |
```suggestion
| type        | User type (`normal` or `admin`, _see [User](/influxdb/v1.6/concepts/glossary/#user)_)        |
```

2021-06-09 14:02 UTC, merged