Kapacitor authorization and authentication
influxdata/docs-v2 pull request #2717
Opened 2021-06-15 22:22 UTC by sanderson

Closes #2690 

- [x] Tests pass (no build errors)
- [x] Rebased/mergeable

2021-06-16 17:40 UTC, jstirnaman requested changes

2021-06-16 23:07 UTC, kelseiv commented on content/kapacitor/v1.6/user-types-permissions.md
> +  View Kapaictor user types and permissions available when using internal
```suggestion
  View Kapacitor user types and permissions available when using internal
```

2021-06-16 23:07 UTC, kelseiv commented on content/kapacitor/v1.6/administration/auth/_index.md
> +  # Enable authentication for Kapacitor
```suggestion
  # Enable authentication for Kapacitor.
```

2021-06-16 23:07 UTC, kelseiv commented on content/kapacitor/v1.6/administration/auth/_index.md
> +  # Enable authentication for Kapacitor
Or all comments w/o

2021-06-17 04:04 UTC, sanderson commented on content/kapacitor/v1.6/administration/auth/influxdb-enterprise-auth.md
> +seotitle: Authenticate with Kapacitor using InfluxDB Enterprise
This is too long of an SEO title. The greatest weight is placed on the first 4 words of a page title.

2021-06-17 04:04 UTC, sanderson commented on content/kapacitor/v1.6/administration/auth/influxdb-enterprise-auth.md
> +- [Chronograf](/{{< latest "chronograf" >}}/) _(to aid in the creation of users and roles)_
Yes, it is optional, but not covered in this doc. It is linked to later.

2021-06-17 04:04 UTC, sanderson commented on content/kapacitor/v1.6/administration/auth/influxdb-enterprise-auth.md
> +- [Authenticate with Kapacitor](#authenticate-with-kapacitor)
I thought about pulling this content into it's own page, but it's only applicable to this specific use case (using InfluxDB Ent auths to auth with Kapacitor). That's why I left it here.

2021-06-17 04:04 UTC, sanderson commented on content/kapacitor/v1.6/administration/auth/kapacitor-auth.md
> +title: Use internal Kapacitor authorizations
Good call. I can do that.

2021-06-17 17:58 UTC, kelseiv approved these changes

2021-06-17 22:16 UTC, merged