Add OSS-Enterprise migration guide to 1.9
influxdata/docs-v2 pull request #2994
Opened 2021-08-09 21:51 UTC by pierwill

Closes #2993.

This adds the migration guide present in Enterprise 1.8 docs to 1.9.

However, I'm not sure this guide can work as a drop in replacement. This might be the reason it wasn't copied over during the 1.9 release. For instance, the requirement that "Your **OSS and Enterprise version is the same**, for example, InfluxDB 1.8 and InfluxDB Enterprise 1.8" on line 20. Does this still hold?

- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2021-08-10 00:18 UTC, timhallinflux requested changes

2021-08-10 00:18 UTC, timhallinflux commented on content/enterprise_influxdb/v1.9/guides/migration.md
> +- Your **OSS and Enterprise version is the same**, for example, InfluxDB 1.8 and InfluxDB Enterprise 1.8.
I'm unclear why An InfluxDB Enterprise cluster running 1.7.10 or later is a pre-requisite.  I believe the instructions have the user install and setup the InfluxDB Enterprise meta nodes.  However, I think these instructions are kind of confusing.  I believe we should have two separate guides.... one for upgrading OSS to Enterprise (where the Enterprise setup is "fresh") and another for adding an OSS node to an existing InfluxDB Enterprise installation (some what more rare...but there are other considerations when doing this -- like rebalancing).  

The version numbers between OSS and Enterprise will no longer be the same.  So, we can suggest that the user ensure that they are running on at least 1.8.x and preferably 1.8.latest.
InfluxDB Enterprise will be 1.9 (which is the current release).

Also, after the upgrade --- I think the rebalancing steps are potentially confusing?  different steps for a 2 data node cluster vs. a 4...   (there isn't much rebalancing to do for a 2 node cluster other than -> 1. Use the [ALTER RETENTION POLICY](/influxdb/v1.9/query_language/manage-database/#modify-retention-policies-with-alter-retention-policy) statement to increase the [replication factor](/enterprise_influxdb/v1.9/concepts/glossary/#replication-factor) on all existing retention polices to the number of data nodes in your cluster._

2021-08-16 19:36 UTC, pierwill commented
Doc has been edited: cleaned up formatting, fixed links, etc.

Changed the instructions saying version numbers must match to say that users should upgrade to latest versions.

2021-09-01 17:12 UTC, kelseiv commented on content/enterprise_influxdb/v1.9/guides/migration.md
> +
@pierwill lets pull up content from "Stop writes and remove OSS" out of the hidden section

2021-09-03 15:01 UTC, kelseiv approved these changes

2021-09-03 15:01 UTC, kelseiv commented on content/enterprise_influxdb/v1.9/guides/migration.md
> +    Double check that the service is stopped.
```suggestion
    3. Double check that the service is stopped.
```

2021-09-03 15:01 UTC, kelseiv commented on content/enterprise_influxdb/v1.9/guides/migration.md
> +3. Remove the InfluxDB OSS package.
```suggestion
4. Remove the InfluxDB OSS package.
```

2021-09-03 15:37 UTC, merged