Document IoT common queries
influxdata/docs-v2 pull request #3013
Opened 2021-08-11 23:20 UTC by mluu12

Closes https://github.com/influxdata/docs-v2/issues/2280

Currently rearranging the common queries document to include scenarios. 

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2021-09-22 22:30 UTC, sanderson requested changes

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +Through all four stations, the `timeWeightedAverages` are 40.25, 40.6, 41.38, 41.27, respectively.
```suggestion
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +In this example, the `_value` in the table below shows output data from the `temperature` field in the `machinery` measurement. The function `timeWeightedAvg` takes the average of the temperature eve
```suggestion
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +| g4        | 2021-08-01T01:00:00.000Z | 2021-08-01T00:00:30.000Z | 41.26735518634935  |
```suggestion
##### Output data

| stationID | _start                   | _stop                    | _value             |
|:-----     | -----                    | -----                    |             ------:|
| g1        | 2021-08-01T01:00:00.000Z | 2021-08-01T00:00:30.000Z | 40.25396118491921  |
| g2        | 2021-08-01T01:00:00.000Z | 2021-08-01T00:00:30.000Z | 40.6               |
| g3        | 2021-08-01T01:00:00.000Z | 2021-08-01T00:00:30.000Z | 41.384505595567866 |
| g4        | 2021-08-01T01:00:00.000Z | 2021-08-01T00:00:30.000Z | 41.26735518634935  |
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +The following scenario queries data starting when the four production lines starts and ends. The following query  calculates the average oil temperature value during that period.
```suggestion
The following scenario queries data starting when four production lines start and end.
The following query  calculates the average oil temperature value during that period.
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +{{% /note %}}
```suggestion
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +Through all four stations, the `means()` are 40, 40.6, 41.38, 41.2, respectively.
```suggestion
##### Output

| stationID | _start                   | _stop                    | _value             |
|:-----     | -----                    | -----                    |             ------:|
| g1        | 2021-08-01T01:00:00.000Z | 2021-08-02T00:00:00.000Z | 40                 |
| g2        | 2021-08-01T01:00:00.000Z | 2021-08-02T00:00:00.000Z | 40.6               |
| g3        | 2021-08-01T01:00:00.000Z | 2021-08-02T00:00:00.000Z | 41.379999999999995 |
| g4        | 2021-08-01T01:00:00.000Z | 2021-08-02T00:00:00.000Z | 41.2               |
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +Equipment speed measurements are recorded periodically (float), as is the production order number (string), but not as a field set – as separate streams. I would like to query the equipment speed mea
Leave this one out for now.

```suggestion
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +| 2021-08-02T00:00:00.000Z | true             | 88.61785638936534  | 108.25471698113208 | -19.636860591766734 | g4        |
```suggestion
| _time                    | needsMaintenance |           pressure |    pressure_target |        pressureDiff | stationID |
| :----------------------- | :--------------- | -----------------: | -----------------: | ------------------: | --------: |
| 2021-08-01T12:00:00.000Z | false            | 101.83929080014092 | 104.37786394078252 | -2.5385731406416028 |        g1 |
| 2021-08-02T00:00:00.000Z | false            |  96.04368008245874 | 102.27698650674662 |  -6.233306424287889 |        g1 |
| 2021-08-01T12:00:00.000Z | false            | 101.62490431541765 | 104.83915260886623 |  -3.214248293448577 |        g2 |
| 2021-08-02T00:00:00.000Z | false            |  94.52039415465273 | 105.90869375273046 | -11.388299598077722 |        g2 |
| 2021-08-01T12:00:00.000Z | false            |  92.23774168403503 | 104.81867444768653 | -12.580932763651504 |        g3 |
| 2021-08-02T00:00:00.000Z | true             |  89.20867846153847 |  108.2579185520362 | -19.049240090497733 |        g3 |
| 2021-08-01T12:00:00.000Z | false            |  94.40834093349847 |  107.6827757125155 | -13.274434779017028 |        g4 |
| 2021-08-02T00:00:00.000Z | true             |  88.61785638936534 | 108.25471698113208 | -19.636860591766734 |        g4 |
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +The following scenario groups together data by one or more context values that creates changes in the state.
```suggestion
## Determine a state with existing values

Use multiple existing values to determine a state.
The following example calculates a state based on the difference between the `pressure` and `pressure-target` fields in the machine-production sample data.
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +{{% /note %}}
```suggestion
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> + The first `map` function takes the difference from `pressure` and `pressure_target`. In order to see the fields' relation to the state change, the second `map` function states that if the absolute v
```suggestion
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +
~~~suggestion
To determine a state by comparing existing fields:

1. Query the fields to compare (in this case, `pressure` and `pressure_target`).
2. (Optional) Use `aggregateWindow()` to window data into time-based windows and
    apply an aggregate function (like `mean()`) to return values that represent larger windows of time.
3. Use `pivot()` to shift field values into columns.
4. Use `map()` to compare or operate on the different field column values.
5. Use `map()` to assign a status (in this case, `needsMaintenance` based on the relation ship of the field column values.
 
~~~

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> + Given the query above, the output is as shown:
```suggestion
##### Output
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/operate-on-columns.md
> +  - Uses [`keep()`](/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/keep/) and [`unique()`](/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/selectors/unique/) to return un
```suggestion
  - Uses [`group()`](/{{< latest "flux" >}}/stdlib/universe/group/) to ungroup data and return results in a single table.
  - Uses [`keep()`](/{{< latest "flux" >}}/stdlib/universe/keep/) and [`unique()`](/{{< latest "flux" >}}/stdlib/universe/selectors/unique/) to return unique values in the specified column.
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/operate-on-columns.md
> +- Uses [`keep()`](/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/keep/), [`unique()`](/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/selectors/unique/), and then [`count
```suggestion
- Uses [`group()`](/{{< latest "flux" >}}/stdlib/universe/group/) to ungroup data and return results in a single table.
- Uses [`keep()`](/{{< latest "flux" >}}/stdlib/universe/keep/), [`unique()`](/{{< latest "flux" >}}/stdlib/universe/unique/), and then [`count()`](/{{< latest "flux" >}}/stdlib/universe/count/) to count the number of unique values.
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/operate-on-columns.md
> + Use the `map()` function to create a new column calculated from existing values in each row.
These seem out of place.

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/operate-on-columns.md
> +Recalculate the `_value` column without creating a new one. Use the `with` operator in [`map()`](/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/map/) to overwrite the existing `_value`
```suggestion
Recalculate the `_value` column without creating a new one. Use the `with` operator in [`map()`](/{{< latest "flux" >}}/stdlib/universe/map/) to overwrite the existing `_value` column.
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/operate-on-columns.md
> +  - Uses [`map()`](/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/map/) to convert Fahrenheit temperature values into Celsius.
```suggestion
  - Uses [`filter()`](/{{< latest "flux" >>}}/stdlib/universe/filter/) to filter the `average_temperature` measurement.
  - Uses [`map()`](/{{< latest "flux" >>}}/stdlib/universe/map/) to convert Fahrenheit temperature values into Celsius.
```

2021-09-22 22:30 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/operate-on-columns.md
> +  - Uses [`map()`](/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/map/) to create a new column calculated from existing values in each row.
```suggestion
  - Uses [`filter()`](/{{< latest "flux" >}}/stdlib/universe/filter/) to filter the `average_temperature` measurement.
  - Uses [`map()`](/{{< latest "flux" >}}/stdlib/universe/map/) to create a new column calculated from existing values in each row.
```

2021-09-24 15:18 UTC, sanderson requested changes

2021-09-24 15:18 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +The results 88.66% of time is in the true state and 11.34% of time is in the false state.
```suggestion
The query above focuses on a specific time range of state changes reported in the production line.
`range()` defines the time range to query.
`filter()` defines the field (`state`) and measurement (`machinery`) to filter by.
`events.duration()` calculates the time between points.
`group()` regroups the data by the field value, so points with `OK` and `NOK` field values are grouped
into separate tables.
`sum()` returns the sum of durations spent in each state.

The output of the query at this point is:

| _value | duration | 
| ------ | -------: | 
| NOK    | 22       | 

| _value | duration | 
| ------ | -------: | 
| OK     | 172      | 

`pivot()` shifts creates columns for each unique value in the `_value` column and then assigns the associated duration as the column value.
The output of the pivot operation is:

| NOK               | OK                 | 
| :---------------- | :----------------- | 
| 11.34020618556701 | 88.65979381443299  | 

Given the output above, `map()` does the following:

1. Adds the `NOK` and `OK` values to calculate `totalTime`. 
2. Divides `NOK` by `totalTime`, and then multiplies the quotient by 100. 
3. Divides `OK` by `totalTime`, and then multiplies the quotient by 100. 

The results is that 88.66% of time is in the `OK` state and 11.34% of time is in the `NOK` state.
```

2021-09-24 15:18 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +
```suggestion
```

2021-09-24 15:18 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +The following query calculates the average oil temperature value during that period.
```suggestion
The following query calculates the average oil temperature for each grinding station during that period.
```

2021-09-24 15:18 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +| 2021-08-02T00:00:00.000Z | true             |  88.61785638936534 | 108.25471698113208 | -19.636860591766734 |        g4 |
```suggestion
| _time                    | needsMaintenance |           pressure |    pressure_target |        pressureDiff | stationID |
| :----------------------- | :--------------- | -----------------: | -----------------: | ------------------: | --------: |
| 2021-08-01T12:00:00.000Z | false            | 101.83929080014092 | 104.37786394078252 | -2.5385731406416028 |        g1 |
| 2021-08-02T00:00:00.000Z | false            |  96.04368008245874 | 102.27698650674662 |  -6.233306424287889 |        g1 |

| _time                    | needsMaintenance |           pressure |    pressure_target |        pressureDiff | stationID |
| :----------------------- | :--------------- | -----------------: | -----------------: | ------------------: | --------: |
| 2021-08-01T12:00:00.000Z | false            | 101.62490431541765 | 104.83915260886623 |  -3.214248293448577 |        g2 |
| 2021-08-02T00:00:00.000Z | false            |  94.52039415465273 | 105.90869375273046 | -11.388299598077722 |        g2 |

| _time                    | needsMaintenance |           pressure |    pressure_target |        pressureDiff | stationID |
| :----------------------- | :--------------- | -----------------: | -----------------: | ------------------: | --------: |
| 2021-08-01T12:00:00.000Z | false            |  92.23774168403503 | 104.81867444768653 | -12.580932763651504 |        g3 |
| 2021-08-02T00:00:00.000Z | true             |  89.20867846153847 |  108.2579185520362 | -19.049240090497733 |        g3 |

| _time                    | needsMaintenance |           pressure |    pressure_target |        pressureDiff | stationID |
| :----------------------- | :--------------- | -----------------: | -----------------: | ------------------: | --------: |
| 2021-08-01T12:00:00.000Z | false            |  94.40834093349847 |  107.6827757125155 | -13.274434779017028 |        g4 |
| 2021-08-02T00:00:00.000Z | true             |  88.61785638936534 | 108.25471698113208 | -19.636860591766734 |        g4 |
```

2021-09-24 15:18 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/operate-on-columns.md
> + Use the `map()` function to create a new column calculated from existing values in each row.
```suggestion
```

2021-09-24 15:18 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/operate-on-columns.md
> +Recalculate the `_value` column without creating a new one. Use the `with` operator in [`map()`](/{{< latest "flux" >}}/stdlib/universe/map/) to overwrite the existing `_value` column.
```suggestion
To recalculate the `_value` column, use the `with` operator in [`map()`](/{{< latest "flux" >}}/stdlib/universe/map/) to overwrite the existing `_value` column.
```

2021-09-24 15:18 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/operate-on-columns.md
> +This example converts temperature from Fahrenheit to Celsius and maps the Celsius value to a new `celsius` column.
```suggestion
To use values in a row to calculate and add a new column, use `map()`.
This example below converts temperature from Fahrenheit to Celsius and maps the Celsius value to a new `celsius` column.
```

2021-09-27 15:49 UTC, sanderson approved these changes
Just some final updates and I think it's good to go.

2021-09-27 15:49 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +`pivot()` shifts creates columns for each unique value in the `_value` column and then assigns the associated duration as the column value.
```suggestion
`pivot()` creates columns for each unique value in the `_value` column and then assigns the associated duration as the column value.
```

2021-09-27 15:49 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +The results is that 88.66% of time is in the `OK` state and 11.34% of time is in the `NOK` state.
```suggestion
The output of the pivot operation is:

| NOK | OK  |
| :-- | :-- |
| 22  | 172 |

Given the output above, `map()` does the following:

1. Adds the `NOK` and `OK` values to calculate `totalTime`. 
2. Divides `NOK` by `totalTime`, and then multiplies the quotient by 100. 
3. Divides `OK` by `totalTime`, and then multiplies the quotient by 100.

This returns:

| NOK               | OK                 | 
| :---------------- | :----------------- | 
| 11.34020618556701 | 88.65979381443299  | 

The results is that 88.66% of time is in the `OK` state and 11.34% of time is in the `NOK` state.
```

2021-09-27 15:49 UTC, sanderson commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +When visualizing data, it is possible to have more data points than available pixels.
~~~suggestion
```

When visualizing data, it is possible to have more data points than available pixels.
~~~

2021-09-29 03:36 UTC, kelseiv approved these changes

2021-09-29 03:36 UTC, kelseiv commented on content/influxdb/cloud/query-data/common-queries/compare-metrics.md
> +title: Comparing metrics from different buckets
```suggestion
title: Compare metrics from different buckets
```

2021-09-29 03:36 UTC, kelseiv commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +To calculate the percentage of time machines in a production line spend in each state:
```suggestion
**To calculate the percentage of time a machine spends in each state**
```

2021-09-29 03:36 UTC, kelseiv commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +2. Use `events.duration()` to return the amount of time (in a specified unit) between each data point and store it in the `duration` column.
```suggestion
2. Use `events.duration()` to return the amount of time (in a specified unit) between each data point, and store the interval in the `duration` column.
```

2021-09-29 03:36 UTC, kelseiv commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +4. Sum the `duration` column to calculated the total amount of time spent in each state.
```suggestion
4. Sum the `duration` column to calculate the total amount of time spent in each state.
```

2021-09-29 03:36 UTC, kelseiv commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +5. Pivot the summed durations into the `_value` column
```suggestion
5. Pivot the summed durations into the `_value` column.
```

2021-09-29 03:36 UTC, kelseiv commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +`sum()` returns the sum of durations spent in each state.
```suggestion

- `range()` defines the time range to query.
- `filter()` defines the field (`state`) and measurement (`machinery`) to filter by.
- `events.duration()` calculates the time between points.
- `group()` regroups the data by the field value, so points with `OK` and `NOK` field values are grouped into separate tables.
- `sum()` returns the sum of durations spent in each state.
```

2021-09-29 03:36 UTC, kelseiv commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +`pivot()` creates columns for each unique value in the `_value` column and then assigns the associated duration as the column value.
```suggestion
`pivot()` creates columns for each unique value in the `_value` column, and then assigns the associated duration as the column value.
```

2021-09-29 03:36 UTC, kelseiv commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +The results is that 88.66% of time is in the `OK` state and 11.34% of time is in the `NOK` state.
```suggestion
The result shows that 88.66% of time production is in the `OK` state, and that 11.34% of time, production is in the `NOK` state.
```

2021-09-29 03:36 UTC, kelseiv commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +The [mosaic visualization](/influxdb/v2.0/visualize-data/visualization-types/mosaic/) displays state changes over time. In this example, the mosaic visualization displayed different colored tiles bas
```suggestion
The [mosaic visualization](/influxdb/v2.0/visualize-data/visualization-types/mosaic/) displays state changes over time. In this example, the mosaic visualization displays different colored tiles based on the `state` field. 
```

2021-09-29 03:36 UTC, kelseiv commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +into time windows that span a single pixel.
```suggestion
When visualizing data, it is possible to have more data points than available pixels. To divide data into time windows that span a single pixel, use `aggregateWindow` with the `every` parameter set to `v.windowPeriod`.
```

2021-09-29 03:36 UTC, kelseiv commented on content/influxdb/v2.0/query-data/common-queries/iot-common-queries.md
> +5. Use `map()` to assign a status (in this case, `needsMaintenance` based on the relation ship of the field column values.
```suggestion
5. Use `map()` to assign a status (in this case, `needsMaintenance` based on the relationship of the field column values.
```

2021-09-29 05:44 UTC, merged