Make edits to the demo data section
influxdata/docs-v2 pull request #3020
Opened 2021-08-16 08:28 UTC by mluu12

Closes https://github.com/influxdata/docs-v2/issues/1385

Moved demo data section to its own file, and organized the write data index. 

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2021-08-17 19:57 UTC, kelseiv commented on content/influxdb/cloud/get-started.md
> +- **InfluxDB Cloud region URL** – _See [InfluxDB Cloud regions](/influxdb/cloud/reference/regions/)_.
```suggestion
```

2021-08-24 16:24 UTC, kelseiv commented on content/influxdb/cloud/write-data/developer-tools/line-protocol.md
> +Use line protocol to write data to InfluxDB Cloud. Line protocol is a is a text-based format that provides the measurement, tag set, field set, and timestamp of a data point. Learn more about [line p
```suggestion
Use line protocol to write data to InfluxDB Cloud. Line protocol is a text-based format that provides the measurement, tag set, field set, and timestamp of a data point. Learn more about [line protocol](/influxdb/v2.0/reference/syntax/line-protocol/). 
```

2021-08-24 16:24 UTC, kelseiv commented on content/influxdb/cloud/write-data/developer-tools/line-protocol.md
> +4. Select your **Precision** in the dropdown menu. By default, the precision is set to nanosections.
```suggestion
4. Select your **Precision** in the dropdown menu. By default, the precision is set to nanoseconds. 
```

2021-08-24 16:24 UTC, kelseiv commented on content/influxdb/cloud/write-data/developer-tools/line-protocol.md
> +## Influx write command
```suggestion
## Write line protocol using the influx write command
```

2021-08-24 16:24 UTC, kelseiv commented on content/influxdb/cloud/write-data/developer-tools/line-protocol.md
> +influx write -b example-bucket -f path/to/example.csv
```suggestion
influx write -b example-bucket -f path/to/example.txt 
```

2021-08-24 16:24 UTC, kelseiv commented on content/influxdb/cloud/write-data/developer-tools/line-protocol.md
> +Set the path for your `--file` flag and set the path for your `--format`.
```suggestion
Set the path to the line protocol file using the `-f` flag.
```

2021-08-24 16:24 UTC, kelseiv commented on content/influxdb/cloud/write-data/developer-tools/line-protocol.md
> +Verify that your line protocol follows the correct conventions.
```suggestion
Verify that your line protocol follows the correct [line protocol format](#line-protocol-format) conventions. 
```

2021-09-21 22:41 UTC, sanderson requested changes

2021-09-21 22:41 UTC, sanderson commented on content/influxdb/cloud/get-started.md
> +   - Use your own data to explore Cloud. See how to [write your data](/influxdb/cloud/write-data/) to Cloud.
```suggestion
   - [Use your own data](/influxdb/cloud/write-data/) to explore InfluxDB Cloud.
```

2021-09-21 22:41 UTC, sanderson commented on content/influxdb/cloud/get-started.md
> +     5. (Optional) [Output to a new bucket and export as a task](#output-to-a-new-bucket-and-export-as-a-task)
```suggestion
2. [Create a notebook](#create-a-notebook):
    1.  Clicking **Books > Create Notebook** in the navigation menu on the left.
        {{< nav-icon "books" >}}
    2. [Select metrics](#select-metrics)
    3. [Visualize data](#visualize-data)
    4. (Optional) [Process data](#process-data)
    5. (Optional) [Monitor data](#monitor-data)
    6. (Optional) [Output to a new bucket and export as a task](#output-to-a-new-bucket-and-export-as-a-task)
```

2021-09-21 22:41 UTC, sanderson commented on content/influxdb/cloud/get-started.md
> +For example purposes, we will be referencing the [NOAA water sample data](/influxdb/v2.0/reference/sample-data/#noaa-water-sample-data), but we provide other [sample data sets](/influxdb/cloud/refere
```suggestion
The examples below use the [NOAA NDBC sample data](/influxdb/v2.0/reference/sample-data/#noaa-ndbc-data), but we provide other [sample data sets](/influxdb/cloud/reference/sample-data/#sample-datasets) as well.
```

2021-09-21 22:41 UTC, sanderson commented on content/influxdb/cloud/get-started.md
> +
```suggestion
### Add sample data with community templates 

1. Visit the **InfluxDB templates page** in the InfluxDB Cloud UI. Click **Settings** > **Templates** in the navigation menu on the left.

    {{< nav-icon "settings" >}}
      
2. Paste the Sample Data community temple URL in **resource manifest file** field:

    ```
    https://github.com/influxdata/community-templates/blob/master/sample-data/sample-data.yml
    ```

The sample data template installs a task that collects sample data and dashboards to visualize the sample data.
After installing the template, sample data is downloaded and stored in the sample data bucket at regular intervals.
```

2021-09-21 22:41 UTC, sanderson commented on content/influxdb/cloud/get-started.md
> +### Add sample data in InfluxDB Cloud UI
```suggestion
### Write sample data with an InfluxDB task
```

2021-09-21 22:41 UTC, sanderson commented on content/influxdb/cloud/get-started.md
> +   - [Download using the InfluxData UI](#add-sample-data-with-influxdata-ui)
```suggestion
  - [Write sample data with an InfluxDB task](#write-sample-data-with-an-influxdb-task)
```

2021-09-21 22:41 UTC, sanderson commented on content/influxdb/cloud/get-started.md
> +4. Click **Submit**.
```suggestion
Use the [Flux InfluxDB sample package](/{{< latest "flux" >}}/stdlib/influxdata/influxdb/sample/) to download and write sample data to InfluxDB.
Add the following as an [InfluxDB task](/influxdb/cloud/process-data/manage-tasks/create-task/).

```js
import "influxdata/influxdb/sample"

option task = {
  name: "Collect NOAA NDBC data"
  every: 15m,
}

sample.data(set: "noaa")
  |> to(bucket: "noaa"  )
    ```
For more information about this and other InfluxDB sample datasets, see [InfluxDB sample data](/influxdb/cloud/reference/sample-data/). 
```

2021-09-21 22:41 UTC, sanderson commented on content/influxdb/cloud/get-started.md
> +3. In the **Every Window Period** field, enter a value. For this example, we'll use `3h30s`, but any duration is supported by InfluxDB Cloud. For more information, see [duration literals](/influxdb/v
```suggestion
3. In the **Every Window Period** field, enter a value. For this example, we'll use `3h30s`, but any duration is supported by InfluxDB Cloud. For more information, see [duration literals](/{{< latest "flux" >}}/spec/lexical-elements/#duration-literals).
```

2021-09-21 22:41 UTC, sanderson commented on content/influxdb/cloud/get-started.md
> +1. Click **+** to add a cell, then select **Output > Alert**.
```suggestion
1. In your notebook, click **{{< icon "plus" >}}** to add a cell, then select **Output > Alert**.
```

2021-09-22 15:37 UTC, sanderson approved these changes

2021-09-27 16:57 UTC, kelseiv approved these changes

2021-09-29 03:39 UTC, kelseiv approved these changes

2021-09-29 05:50 UTC, merged