updated the email docs
influxdata/docs-v2 pull request #3051
Opened 2021-08-22 11:13 UTC by smzgit

single & double quotes in tickscript hold different meanings. In cpu_alert.tick tickscript 'usage_idle' must be enclosed within double quotes,ie., "usage_idle", otherwise kapacitor throws error -> enabling task cpu_alert: Failed to compile stateful expression for crit: mismatched type to binary operator. got string < int. see bool(), int(), float(), string(), duration()

Closes #

_Describe your proposed changes here._

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2021-08-25 16:56 UTC, smzgit commented
@jstirnaman can you please review this pull request? Thanks!

2021-08-29 07:08 UTC, smzgit commented
@jstirnaman  yeah exactly! Actually when i tried the same example without casting then it didn't work & throws error : mismatched type to binary operator. got string < int. 
And in another example - i found that same field was casted & it worked, i thought its some documentation mistake thats why i made the PR.

2021-08-30 16:52 UTC, sanderson requested changes
Thanks for this @smzgit. I think we should remove the `int` casting from this example. It isn't necessary. In TICKscript, single quotes enclose string literals and double quotes are used to access field and tag values. The `mismatched type to binary operator. got string < int` error you got must have come from `'usage_idle` > 10` because that's comparing a string literal to an integer. You shouldn't get that error from `"usage_idle" < 10` unless the `usage_idle` field contains string values, which it definitely shouldn't.

2021-08-30 16:52 UTC, sanderson commented on content/kapacitor/v1.6/event_handlers/email.md
> +    .crit(lambda: int("usage_idle") < 10)
```suggestion
    .crit(lambda: "usage_idle" < 10)
```

2021-08-31 05:31 UTC, smzgit commented
Thanks @sanderson  for the suggestion, `int()` casting was required there, applied the suggested change.

2021-08-31 14:12 UTC, jstirnaman approved these changes

2021-08-31 14:12 UTC, jstirnaman commented
LGTM!

2021-08-31 14:49 UTC, sanderson approved these changes

2021-08-31 14:49 UTC, merged