Note `from()` can query remote sources
influxdata/docs-v2 pull request #3074
Opened 2021-08-27 20:29 UTC by pierwill

Closes #3073.

- [x] Tests pass (no build errors)
- [x] Rebased/mergeable

2021-08-30 14:50 UTC, sanderson requested changes
The change looks good, but I think we should add some details to the existing params in the doc. I'd add suggestions, but GitHub won't let me since the params weren't modified in the PR. Here are my recommendations:

```md
### bucket
Name of the bucket to query.

**InfluxDB 1.x or Enterprise**: provide an empty string (`""`)

_**Data type:** String_

### bucketID
String-encoded bucket ID to query.

**InfluxDB 1.x or Enterprise**: provide an empty string (`""`)

_**Data type:** String_

### host
URL of the InfluxDB instance to query.
_See [InfluxDB URLs](/influxdb/v2.0/reference/urls/)._

_**Data type:** String_

### org
Organization name.

**InfluxDB 1.x or Enterprise**: provide an empty string (`""`)

_**Data type:** String_

### orgID
String-encoded [organization ID](/influxdb/v2.0/organizations/view-orgs/#view-your-organization-id) to query.

**InfluxDB 1.x or Enterprise**: provide an empty string (`""`)

_**Data type:** String_

### token
InfluxDB [API token](/influxdb/v2.0/security/tokens/).

**InfluxDB 1.x or Enterprise**: If authentication is _disabled_, provide an empty string (`""`). If authentication is _enabled_, provide your InfluxDB username and password using the `<username>:<password>` syntax.

_**Data type:** String_
```

2021-08-30 21:55 UTC, lesam commented on content/influxdb/v2.0/reference/flux/stdlib/built-in/inputs/from.md
> -`from()` **cannot retrieve data** from **remote** InfluxDB OSS 1.x or InfluxDB Enterprise 1.x data sources
I think we should specifically call out 1.9+ here.

2021-08-31 16:36 UTC, sanderson approved these changes
One minor change and I think it's gtg 👍🏻

2021-08-31 16:36 UTC, sanderson commented on content/influxdb/v2.0/reference/flux/stdlib/built-in/inputs/from.md
> +(InfluxDB 1.x OSS and Enterprise 1.9+ are also supported.)
```suggestion
Use `from()` to retrieve data from remote InfluxDB OSS 1.7+, InfluxDB Enterprise 1.9+, and InfluxDB Cloud.
```

2021-08-31 17:00 UTC, merged