Document replicating a Cloud organization
influxdata/docs-v2 pull request #3147
Opened 2021-09-20 16:01 UTC by pierwill

Closes #3067
- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2021-09-22 20:47 UTC, gunnaraasen reviewed
Just a few small comments, otherwise this looks great and exactly what I had in mind.

2021-09-22 20:47 UTC, gunnaraasen commented on content/influxdb/cloud/organizations/migrate-org.md
> +Rate limiting may apply.
Do we have a doc we could link about how to identify rate limit errors?

2021-09-22 20:47 UTC, gunnaraasen commented on content/influxdb/cloud/organizations/migrate-org.md
> +To duplicate the state of an organization:
I think a quick summary explanation would help set context for the following steps. E.g. an org's state consists of both metadata resources (dashboards, buckets, etc) and the data (time-series).

2021-09-22 20:47 UTC, gunnaraasen commented on content/influxdb/cloud/organizations/migrate-org.md
> +
Might want to add a note that points to a migration doc for InfluxDB v1 to v2.

2021-09-23 20:28 UTC, gunnaraasen requested changes
Looking good. Almost there.

2021-09-23 20:28 UTC, gunnaraasen commented on content/influxdb/cloud/organizations/migrate-org.md
> +the state of an organization can be migrated to a new organization.
I'm not sure this is correct. Migrating the entire metadata and data state of an organization is effectively duplicating the org. Maybe something along the lines of:

An organization's state at a point in time can be effectively duplicated to another organization by copying both metadata and data. Copying only metadata can be useful for replicating the state of an organization for different environments, e.g. dev and prod. Copying only data can be useful for saving high value data to a location not subject to a retention policy.

2021-09-27 20:23 UTC, kelseiv approved these changes

2021-09-27 20:23 UTC, kelseiv commented on content/influxdb/cloud/organizations/migrate-org.md
> +1. Perform a query to return all desired data.
```suggestion
1. Perform a query to return all specified data.
```

2021-09-27 20:23 UTC, kelseiv commented on content/influxdb/cloud/organizations/migrate-org.md
> +   (This requires copying data to a location outside of InfluxDB Cloud.)
```suggestion
2. Save the results as CSV (to a location outside of InfluxDB Cloud.)
```

2021-09-27 20:23 UTC, kelseiv commented on content/influxdb/cloud/organizations/migrate-org.md
> +Perform a query to return all desired data.
```suggestion
Perform a query to return all specified data.
```

2021-09-27 20:23 UTC, kelseiv commented on content/influxdb/cloud/organizations/migrate-org.md
> +flag to control the rate of writes.
```suggestion
If writes are prevented by rate limiting, use the [`influx write --rate-limit`](/influxdb/cloud/reference/cli/influx/write/#write-annotated-csv-data-using-rate-limiting) flag to control the rate of writes.
```

2021-09-27 20:23 UTC, kelseiv commented on content/influxdb/cloud/organizations/migrate-org.md
> +description: Replicate the state of an organization in InfluxDB Cloud
Think we should use the most accurate term, either migrate, duplicate, or replicate; and only use one term to reduce cognitive load (unless there's a distinction we're making here).

2021-09-27 20:38 UTC, merged