Fix csv
influxdata/docs-v2 pull request #3250
Opened 2021-10-15 18:22 UTC by kelseiv

Closes https://github.com/influxdata/docs-v2/issues/3174

2021-11-16 20:29 UTC, jstirnaman requested changes

2021-11-16 20:29 UTC, jstirnaman commented on content/influxdb/v2.0/reference/cli/influx/write/dryrun.md
>  cpu,cpu1,host2,0,2.2,b,1482669087000000000
```suggestion
cpu,cpu1,host2,0,2.2,b,1482669087000000000"
```
As is, this breaks when copy-pasted from the source Markdown (but still works when c-p'd from the browser). Close double quote at end of line and delete from line 144. Alternatively, close this line with ` \` and keep `"` on 144.

2022-01-18 17:13 UTC, kelseiv commented on content/influxdb/v2.0/reference/cli/influx/write/dryrun.md
>  "
```suggestion
```

2022-01-18 21:23 UTC, jstirnaman commented on content/influxdb/v2.0/write-data/developer-tools/csv.md
> +#datatype,group,default,measurement,tag,double,dateTime:RFC3339
- Why "group,default" here?
- Is the extra whitespace in 52-54 intentional?

2023-08-15 14:25 UTC, closed without merging