Fix csv examples
influxdata/docs-v2 pull request #3345
Opened 2021-11-03 21:57 UTC by mcfarlm3

Closes #3174

This PR attempts to address CSV examples which resulted in errors due to incorrect syntax and formatting differences between `influx write` and Flux. My observations after testing the examples, and corresponding changes are listed below.

Observations:
- `influx write` requires a space between the annotation name and annotation values (will error if a comma is added instead), while Flux requires a comma between annotation names and annotation values.
- Flux requires `datatype`, `group`, and `default` annotations. If any of these 3 are missing, it will produce an error.
- Flux requires the `_measurement` column to be present
- The `--skip-headers` flag for `influx write` used to be supported as a bool and int (making `--skip-headers` equivalent to `--skip-headers=1`). Now, this flag is only treated as an integer, meaning that `--skip-headers` is now equivalent to `--skip-headers=0`.

Changes made:
- Fixed Flux CSV example [here](https://docs.influxdata.com/influxdb/v2.0/reference/syntax/annotated-csv/#annotated-csv-in-flux). Now it includes all required annotations and the `_measurement` column. 
- Changed [this](https://docs.influxdata.com/influxdb/v2.0/write-data/developer-tools/csv/#replace-column-header-with-annotation-shorthand) example to reflect the change in the`--skip-headers` flag (default of 0 instead of 1)
-  Added additional information to [this](https://docs.influxdata.com/influxdb/v2.0/write-data/developer-tools/csv/#required-columns) note to try to differentiate what is needed for Flux vs. `influx write` CSV data

The differences between requirements for `influx write` and Flux may still be too ambiguous - if there's more I should add to make those differences clear, feedback would be great.

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Tests pass (no build errors)
- [ ] Rebased/mergeable

2021-11-09 23:35 UTC, sanderson requested changes
Thanks for this @mcfarlm3. Could you also port these changes into the new InfluxDB 2.1 docs.

2021-11-09 23:35 UTC, sanderson commented on content/influxdb/v2.0/reference/syntax/annotated-csv/_index.md
> +#group,false,false,false,false,false,false,false,false,false
The group annotation doesn't accurately reflect the grouping of the csv data.

```suggestion
#group,false,false,true,true,false,true,false,false,true
```

2021-11-09 23:35 UTC, sanderson commented on content/influxdb/v2.0/write-data/developer-tools/csv.md
> +To write CSV data to InfluxDB with Flux, ALL of the following annotations and columns must be present.
```suggestion
To write CSV data to InfluxDB with Flux, _all_ of the following annotations and columns must be present.
```

2021-11-09 23:35 UTC, sanderson commented on content/influxdb/v2.0/write-data/developer-tools/csv.md
> +See [annotations](/influxdb/cloud/reference/syntax/annotated-csv/#annotations) for more information.
```suggestion
See [annotations](/influxdb/v2.0/reference/syntax/annotated-csv/#annotations) for more information.
```

2021-11-11 17:13 UTC, mcfarlm3 commented
> Thanks for this @mcfarlm3. Could you also port these changes into the new InfluxDB 2.1 docs.

Definitely - I can get that done today or tomorrow at the latest. Thanks for the feedback!

2021-11-15 16:32 UTC, sanderson approved these changes
Thanks @mcfarlm3!

2021-11-23 19:11 UTC, kelseiv approved these changes

2021-11-23 19:11 UTC, kelseiv commented on content/influxdb/v2.1/write-data/developer-tools/csv.md
> +Required annotations:
```suggestion
To write CSV data to InfluxDB with Flux, you must include _all_ of the following annotations and columns:
```

2021-11-23 19:11 UTC, kelseiv commented on content/influxdb/v2.1/write-data/developer-tools/csv.md
> +With Flux, there must also be a comma between the annotation name and the annotation values (this differs from the `influx write` command).
```suggestion
With Flux, you must also include a comma between the annotation name and the annotation values (this differs from the `influx write` command).
```

2021-11-23 19:11 UTC, kelseiv commented on content/influxdb/v2.1/write-data/developer-tools/csv.md
> +An example of valid Flux syntax can be found [here](/influxdb/v2.1/reference/syntax/annotated-csv/#annotated-csv-in-flux).
```suggestion
See an example of valid syntax for [annotated CSV in Flux](/influxdb/v2.1/reference/syntax/annotated-csv/#annotated-csv-in-flux).
```

2021-11-23 19:11 UTC, kelseiv commented on content/influxdb/v2.0/write-data/developer-tools/csv.md
> +Required annotations:
```suggestion
To write CSV data to InfluxDB with Flux, you must include _all_ of the following annotations and columns:
```

2021-11-23 19:11 UTC, kelseiv commented on content/influxdb/v2.0/write-data/developer-tools/csv.md
> +With Flux, there must also be a comma between the annotation name and the annotation values (this differs from the `influx write` command).
With Flux, you must also include a comma between the annotation name and the annotation values (this differs from the `influx write` command).

2021-11-23 19:11 UTC, kelseiv commented on content/influxdb/v2.0/write-data/developer-tools/csv.md
> +An example of valid Flux syntax can be found [here](/influxdb/cloud/reference/syntax/annotated-csv/#annotated-csv-in-flux).
```suggestion
See an example of valid syntax for [annotated CSV in Flux](/influxdb/v2.1/reference/syntax/annotated-csv/#annotated-csv-in-flux).
```

2021-11-23 19:19 UTC, merged