Update Create a Notebook
influxdata/docs-v2 pull request #3445
Opened 2021-11-29 20:11 UTC by jstirnaman

Closes #

_Describe your proposed changes here._

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [x] Rebased/mergeable

2021-11-29 23:35 UTC, sanderson requested changes

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +1. In the navigation menu on the left, click **Books** or **Notebooks**.
```suggestion
1. In the navigation menu on the left, click **Notebooks**.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +    - **Schedule a Task**: includes a [Flux Script editor cell]((#add-a-data-source-cell), a [validation cell](#add-a-validation-cell), and a [task schedule cell](#add-an-action-cell).
```suggestion
    - **Schedule a Task**: includes a [Flux Script editor cell](#add-a-data-source-cell), a [validation cell](#add-a-validation-cell), and a [task schedule cell](#add-an-action-cell).
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +2. In the **Notebooks** page, click one of the following options under **Create a Notebook**:
```suggestion
2. In the **Notebooks** page, select one of the following options under **Create a Notebook**:
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +   InfluxDB displays query results in **Validate the Data** and **Visualize the Result** *without writing data or running actions*.
```suggestion
7. {{< oss-only >}}

    Select and click **Preview** (or press **CTRL + Enter**) under the notebook title.
    InfluxDB displays query results in **Validate the Data** and **Visualize the Result** *without writing data or 
    running actions*.
    
    {{< /oss-only >}}
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +10. (Optional) Configure notebook actions (**Alert**, **Task**, or **Output to Bucket**).
```suggestion
10. (Optional) Configure notebook actions {{< oss-only >}}(**Alert**, **Task**, or **Output to Bucket**){{< /oss-only >}}{{< cloud-only >}}(**Alert** or **Task**){{< /cloud-only >}}.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +1. Click the {{< icon "notebook-add-cell" >}}.
```suggestion
1. Click {{< icon "notebook-add-cell" >}}.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +2. Select **Flux Script** or **Query Builder** as your input, and then select or enter the bucket to pull data from.
```suggestion
2. Select **{{< caps >}}Flux Script{{< /caps >}}** or **{{< caps >}}Query Builder{{< /caps >}}** as your input, and then select or enter the bucket to pull data from.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +4. Select **Preview** (**CTRL + Enter**) or **Run** in the upper left dropdown menu.
```suggestion
4. Select {{< oss-only >}}**Preview** (**CTRL + Enter**) or {{< /oss-only >}}**Run** in the upper left drop-down list.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +1. Click the {{< icon "notebook-add-cell" >}}.
```suggestion
1. Click {{< icon "notebook-add-cell" >}}.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +2. Under **Visualization**, click **Table**.
```suggestion
2. Under **Visualization**, click **{{< caps >}}Table{{< /caps >}}**.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +1. Click the {{< icon "notebook-add-cell" >}}.
```suggestion
1. Click {{< icon "notebook-add-cell" >}}.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +   - Note
```suggestion
   - **{{< caps >}}Table{{< /caps >}}**: Display data in tabular format.
   - **{{< caps >}}Graph{{< /caps >}}**: Visualize data using InfluxDB visualizations.
   - **{{< caps >}}Note{{< /caps >}}**: Use Markdown to add notes or other information to your notebook.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +Add an [action cell](/influxdb/v2.1/notebooks/overview/#action) to filter and apply changes to your data, for example, create an [alert](/influxdb/v2.1/monitor-alert/), process data with a [task](/in
```suggestion
Add an [action cell](/influxdb/v2.1/notebooks/overview/#action) to create an [alert](/influxdb/v2.1/monitor-alert/)
{{< cloud-only >}}or{{< /cloud-only >}}{{< oss-only >}},{{< /oss-only >}} process data with a [task](/influxdb/v2.1/process-data/manage-tasks/)
{{< oss-only >}}, or output data to a bucket{{< /oss-only >}}.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +{{% /warn %}}
```suggestion
{{< oss-only >}}

{{% warn %}}
If your cell contains a custom script that uses any output function to write data to InfluxDB (for example: the `to()` function) or sends data to a third-party service, clicking Preview will write data.
{{% /warn %}}

{{< /oss-only >}}
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +- [Add an Output to Bucket cell](#add-an-output-to-bucket-cell)
```suggestion
- {{< oss-only >}}[Add an Output to Bucket cell](#add-an-output-to-bucket-cell){{< /oss-only >}}
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
>     - Pager Duty
```suggestion
   - PagerDuty
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +4. (Optional) Personalize your message. By default, the message is
```suggestion
4. (Optional) Personalize your message. By default, the message is:
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +5. Click **Test Alert** to send a test message to your configured **Endpoint**. The test will not schedule the new alert.
```suggestion
5. Click **{{< caps >}}Test Alert{{< /caps >}}** to send a test message to your configured **Endpoint**. The test will not schedule the new alert.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +6. Click **Export Alert Task** to create your alert.
```suggestion
6. Click **{{< icon "export" >}} {{< caps >}}Export Alert Task{{< /caps >}}** to create your alert.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +### Add an Output to Bucket cell
```suggestion
{{< oss-only >}}
### Add an Output to Bucket cell
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +5. Select and click **Run** in the upper left to write the query result to the bucket.
```suggestion
5. Select and click **Run** in the upper left to write the query result to the bucket.

{{< /oss-only >}}
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +2. Click **Output to Bucket**.
```suggestion
2. Click **{{< caps >}}Output to Bucket{{< /caps >}}**.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +3. In the **Choose a bucket** dropdown menu, select or create a bucket.
```suggestion
3. In the **{{< icon "bucket" >}} Choose a bucket** drop-down list, select or create a bucket.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +8. (Optional) Change your visualization settings with the dropdown menu and the {{< icon "gear" >}} **Configure** button at the top of the **Visualize the Result** cell.
```suggestion
8. (Optional) Change your visualization settings with the drop-down menu and the {{< icon "gear" >}} **Configure** button at the top of the **Visualize the Result** cell.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +- To change your [visualization type](/influxdb/v2.1/visualize-data/visualization-types/), select a new type from the dropdown menu at the top of the cell.
```suggestion
- To change your [visualization type](/influxdb/v2.1/visualize-data/visualization-types/), select a new type from the drop-down list at the top of the cell.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +1. Click the {{% icon "notebook-add-cell" %}}.
```suggestion
1. Click {{% icon "notebook-add-cell" %}}.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +1. Click the {{% icon "notebook-add-cell" %}}.
```suggestion
1. Click {{% icon "notebook-add-cell" %}}.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +2. Click **Task**.
```suggestion
2. Click **{{< caps >}}Task{{< /caps >}}**.
```

2021-11-29 23:35 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +4. Click **Export as Task** to save.
```suggestion
4. Click **{{< icon "task" >}} {{< caps >}}Export as Task{{< /caps >}}** to save.
```

2021-11-30 16:07 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
>     - Pager Duty
I submitted a fix for this to the UI repo (https://github.com/influxdata/ui/pull/3335). "PagerDuty" is the registered trademark name.

2021-11-30 16:21 UTC, jstirnaman commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +2. Click **Task**.
v2.1 buttons aren't uppercase yet.

2021-11-30 16:22 UTC, jstirnaman commented on content/influxdb/v2.1/notebooks/create-notebook.md
> +4. Click **Export as Task** to save.
v2.1 buttons aren't uppercase yet.

2021-11-30 17:22 UTC, sanderson commented on content/influxdb/v2.1/notebooks/create-notebook.md
>     - Pager Duty
This change just got merged into the UI repo, so we're probably good to make it here and future-proof it.

2021-11-30 17:29 UTC, merged