Update 2.x linux installation instructions
influxdata/docs-v2 pull request #3510
Opened 2021-12-20 17:00 UTC by wbaker85

Closes #3509

Clarifies that only one of the two installation steps is necessary (install systemd package OR download binary), also clarifies wording related to the downloaded binary.

I moved the systemd option to come before manually downloading the binary to be symmetrical with the mac instructions.

2021-12-20 23:27 UTC, sanderson requested changes
Added some suggestions.

2021-12-20 23:27 UTC, sanderson commented on content/influxdb/v2.1/install.md
> +- **influx CLI configurations:** `~/.influxdbv2/configs` _(see [`influx config`](/influxdb/v2.1/reference/cli/influx/config/) for more information)_ .
```suggestion
For information about where InfluxDB stores data on disk when running as a service,
see [File system layout](/influxdb/v2.1/reference/internals/file-system-layout/?t=Linux#installed-as-a-package).
```

2021-12-20 23:27 UTC, sanderson commented on content/influxdb/v2.1/install.md
> +### Manually Download and Install Linux Binary
```suggestion
### Manually download and install the influxd binary
```

2021-12-20 23:27 UTC, sanderson commented on content/influxdb/v2.1/install.md
> +- [Manually download and install linux binary](#manually-download-and-install-linux-binary)
```suggestion
- [Manually download and install the influxd binary](#manually-download-and-install-the-influxd-binary)
```

2021-12-20 23:27 UTC, sanderson commented on content/influxdb/v2.1/install.md
> +If InfluxDB was installed as a systemd service, systemd will manage starting and stopping the `influxd` daemon and no further action is required. If the binary was manually downloaded and added to th
```suggestion
If InfluxDB was installed as a systemd service, systemd manages the `influxd` daemon and no further action is required.
If the binary was manually downloaded and added to the system `$PATH`, start the `influxd` daemon with the following command:
```

2021-12-22 15:28 UTC, wbaker85 commented
@sanderson thanks for the suggestions! I incorporated them all. Let me know if there's anything else.

2021-12-22 15:53 UTC, sanderson approved these changes

2021-12-22 16:03 UTC, merged