Feat/2567 monitor oss
influxdata/docs-v2 pull request #3689
Opened 2022-01-18 15:27 UTC by jstirnaman

Closes #2567
Closes #3527 

Add /metrics documentation to existing monitor (with templates) docs.

2022-01-20 20:36 UTC, sanderson requested changes

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Count of bytes returned by the query.
```suggestion
Count of bytes returned by the query endpoint.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of total buckets on the server.
```suggestion
Total number of buckets on the server.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of total dashboards on the server.
```suggestion
Total number of dashboards on the server.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of total organizations on the server.
```suggestion
Total number of organizations on the server.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of total scrapers on the server.
```suggestion
Total number of scrapers on the server.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of total telegraf configurations on the server.
```suggestion
Total number of Telegraf configurations on the server.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of total tokens on the server.
```suggestion
Total number of API tokens on the server.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of total users on the server
```suggestion
Total number of users on the server.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of queries in all states
```suggestion
Number of queries in all states.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of calls.
```suggestion
Number of calls to the bucket creation service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Duration of calls.
```suggestion
Duration of calls to the bucket creation service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of errors encountered.
```suggestion
Number of errors encountered by the bucket creation service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of calls.
```suggestion
Number of calls to the onboarding service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Duration of calls.
```suggestion
Duration of calls to the onboarding service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of calls.
```suggestion
Number of calls to the organization service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Duration of calls.
```suggestion
Duration of calls to the organization service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of calls.
```suggestion
Number of calls to the organization creation service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Duration of calls.
```suggestion
Duration of calls to the organization creation service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of errors encountered.
```suggestion
Number of errors encountered by the organization creation service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of calls.
```suggestion
Number of calls to the password creation service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Duration of calls.
```suggestion
Duration of calls to the password creation service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of errors encountered.
```suggestion
Number of errors encountered by the password creation service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of calls.
```suggestion
Number of calls to the `pkger` service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Duration of calls.
```suggestion
Duration of calls to the `pkger` service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Metrics for resources being exported
```suggestion
Metrics for exported resources.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of calls.
```suggestion
Number of calls to the session service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Duration of calls.
```suggestion
Duration of calls to the session service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of errors encountered.
```suggestion
Number of errors encountered by the session service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of calls.
```suggestion
Number of calls to the token service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Duration of calls.
```suggestion
Duration of calls to the token service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of errors encountered.
```suggestion
Number of errors encountered by the token service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of calls.
```suggestion
### URM new call total
Number of calls to the URM (unified resource management) creation service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Duration of calls.
```suggestion
### urm new duration
Duration of calls to the URM creation service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Number of calls.
```suggestion
### User new call total
Number of calls to the user creation service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Duration of calls.
```suggestion
### User new duration
Duration of calls  to the user creation service.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +The number of errors thrown by the executor with the type of error (ex. Invalid, Internal, etc.)
```suggestion
Number of errors thrown by the executor with the type of error (ex. Invalid, Internal, etc.)
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +The duration in seconds between a run starting and finishing.
```suggestion
Duration (in seconds) between a task run starting and finishing.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Records the latency between the time the run was due to run and the time the task started execution, by task type.
```suggestion
Latency between the time task run's scheduled start times and actual start times, by task type.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +The duration in seconds between a run being due to start and actually starting.
```suggestion
Duration (in seconds) between a task run's scheduled start time and actual start time.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Total number of runs completed across all tasks, split out by success or failure.
```suggestion
Total number of task runs completed across all tasks, split out by success or failure.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +The duration in seconds between a run starting and finishing.
```suggestion
Duration (in seconds) between a task run starting and finishing.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +The duration between when a Item should be scheduled and when it is told to execute.
```suggestion
Delay between when a task is scheduled to run and when it is told to execute.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Total number of times an execution has failed.
```suggestion
Total number of times a scheduled task execution has failed.
```

2022-01-20 20:36 UTC, sanderson commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Total number of executions across all tasks.
```suggestion
Total number of scheduled executions across all tasks.
```

2022-02-07 17:04 UTC, jstirnaman commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Records the latency between the time the run was due to run and the time the task started execution, by task type.
```suggestion
Records the latency between the time the run was due to run and the time the task started execution, by task type.
```
Latency between the task run's scheduled start time and the execution time, by task type.

2022-02-07 17:05 UTC, jstirnaman commented on content/influxdb/v2.1/reference/internals/metrics.md
> +Records the latency between the time the run was due to run and the time the task started execution, by task type.
```suggestion
Latency between the task run's scheduled start time and the execution time, by task type.
```

2022-02-07 17:07 UTC, jstirnaman commented on content/influxdb/v2.1/reference/internals/metrics.md
> +The duration in seconds between a run being due to start and actually starting.
```suggestion
Duraction (in seconds) between the task run's scheduled start time and the execution time,
```

2022-02-07 17:13 UTC, merged