fix: update task run docs with Clockface changes.
influxdata/docs-v2 pull request #3875
Opened 2022-03-21 14:02 UTC by jstirnaman

Closes #3374 

Update remaining task docs in Process Data with Clockface change.

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [x] Rebased/mergeable

2022-04-29 18:09 UTC, noramullen1 requested changes

2022-04-29 18:09 UTC, noramullen1 commented on content/influxdb/v2.1/process-data/manage-tasks/run-task.md
> +2. Find the task you would like to run and click the **{{< icon "settings" >}}** icon located far right of the task name.
I prefer 'want' to 'would like' in all of these cases. It's shorter and less formal. They don't mention it specifically in the Google style guide, but I would argue it's analogous to "wish": https://developers.google.com/style/word-list#wish.

2022-06-17 16:22 UTC, sanderson commented
@jstirnaman Let's either close or merge this PR. It'll need to be ported to 2.2, but it would be nice to get those changes in before we cut 2.3.

2022-06-17 16:31 UTC, sunbryely-influxdata approved these changes

2022-06-17 16:52 UTC, merged