This is for adding InfluxDB University course links to areas of docs.
influxdata/docs-v2 pull request #4102
Opened 2022-06-07 17:51 UTC by peterreg

Closes #

_Describe your proposed changes here._

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Rebased/mergeable

2022-06-07 20:03 UTC, kelseiv requested changes

2022-06-07 20:03 UTC, kelseiv commented on content/enterprise_influxdb/v1.9/introduction/installation/_index.md
> +{{< influxdbu title="Installing InfluxDB Enterprise" summary="In this course you will learn about the architecture concepts for InfluxDB Enterprise and how to install InfluxDB Enterprise with step-by
```suggestion
{{< influxdbu title="Installing InfluxDB Enterprise" summary="Learn about InfluxDB Enterprise architecture and how to install InfluxDB Enterprise." action="Take the course" link="https://university.influxdata.com/courses/installing-influxdb-enterprise-tutorial/" >}}
```
```suggestion
{{< influxdbu title="Installing InfluxDB Enterprise" summary="In this course you will learn about the architecture concepts for InfluxDB Enterprise and how to install InfluxDB Enterprise with step-by-step instructions." action="Take the course" link="https://university.influxdata.com/courses/installing-influxdb-enterprise-tutorial/" >}}
```

2022-06-07 20:03 UTC, kelseiv commented on content/enterprise_influxdb/v1.9/introduction/installation/_index.md
> +{{< influxdbu title="Installing InfluxDB Enterprise" summary="In this course you will learn about the architecture concepts for InfluxDB Enterprise and how to install InfluxDB Enterprise with step-by
```suggestion
{{< influxdbu title="Installing InfluxDB Enterprise" summary="Learn about InfluxDB Enterprise architecture and how to install InfluxDB Enterprise." action="Take the course" link="https://university.influxdata.com/courses/installing-influxdb-enterprise-tutorial/" >}}
```
```suggestion
{{< influxdbu title="Installing InfluxDB Enterprise" summary="In this course you will learn about the architecture concepts for InfluxDB Enterprise and how to install InfluxDB Enterprise with step-by-step instructions." action="Take the course" link="https://university.influxdata.com/courses/installing-influxdb-enterprise-tutorial/" >}}
```

2022-06-07 23:31 UTC, kelseiv approved these changes

2022-06-08 18:59 UTC, sanderson approved these changes
Thanks @peterreg! These are great! Just one minor suggestion on the placement of one of the banners. Otherwise, these are gtg.

2022-06-08 18:59 UTC, sanderson commented on content/enterprise_influxdb/v1.9/flux/get-started/_index.md
> +{{< influxdbu "flux-103" >}}
Move this up above the page nav buttons.

2022-06-09 00:07 UTC, merged