feat: documented invokable scripts within tasks functionality in the CLI
influxdata/docs-v2 pull request #4276
Opened 2022-07-28 21:31 UTC by Xenonic

This PR documents the new flags available to the `create` and `update` subcommands for tasks in the CLI tool. PRs implementing these new features are here: https://github.com/influxdata/influx-cli/pull/432, https://github.com/influxdata/influx-cli/pull/433.

- [x] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [x] Rebased/mergeable

2022-08-01 15:13 UTC, sanderson requested changes
Thanks for this @Xenonic. A few notes:

- This branch needs to be based off the `influx-cli-2.4` branch. 
- These changes should be applied to `/content/influxdb/v2.4/`, not `.../v2.3`.
- Will the new flags only be supported in Cloud or will 2.4 rollout with support for these? If so, we can remove the "Cloud only" flags.

2022-08-01 15:13 UTC, sanderson commented on content/influxdb/v2.3/reference/cli/influx/task/create.md
> +| `-r` | `--cron`          | [Cloud only] Cron expression to define when the task should run       | string     |                       |
```suggestion
| `-r` | `--cron`          | _(InfluxDB Cloud only)_ Cron expression to define when the task runs             | string     |                       |
```

2022-08-01 15:13 UTC, sanderson commented on content/influxdb/v2.3/reference/cli/influx/task/create.md
> +| `-r` | `--cron`          | [Cloud only] Cron expression to define when the task should run       | string     |                       |
Is this really cloud only or will this be supported in InfluxDB 2.4?

2022-08-01 15:13 UTC, sanderson commented on content/influxdb/v2.3/reference/cli/influx/task/create.md
> +| `-e` | `--every`         | [Cloud only] Interval at which the task runs                          | string     |                       |
```suggestion
| `-e` | `--every`         | _(InfluxDB Cloud only)_ Interval at which the task runs                          | string     |                       |
```

2022-08-01 15:13 UTC, sanderson commented on content/influxdb/v2.3/reference/cli/influx/task/create.md
> +| `-n` | `--name`          | [Cloud only] Name of the task                                         | string     |                       |
```suggestion
| `-n` | `--name`          | _(InfluxDB Cloud only)_ Task name                                         | string     |                       |
```

2022-08-01 15:13 UTC, sanderson commented on content/influxdb/v2.3/reference/cli/influx/task/create.md
> +|      | `--script-params` | [Cloud only] JSON parameters for the script to be executed            | string     |                       |
```suggestion
|      | `--script-id`     | _(InfluxDB Cloud only)_ Invokable script ID to execute             | string     |                       |
|      | `--script-params` | _(InfluxDB Cloud only)_ Invokable script JSON parameters            | string     |                       |
```

2022-08-01 15:13 UTC, sanderson commented on content/influxdb/v2.3/reference/cli/influx/task/create.md
> +```
~~~suggestion
##### Create a task using an invokable script
```sh
influx task create \
  --name "my task" \
  --every "10h" \
  --script-id 0001234
```
~~~

2022-08-01 15:13 UTC, sanderson commented on content/influxdb/v2.3/reference/cli/influx/task/update.md
> +|      | `--script-params` | [Cloud only] JSON parameters for the script to be executed            | string     |                       |
```suggestion
|      | `--script-id`     | _(InfluxDB Cloud only)_ Invokable script ID to execute             | string     |                       |
|      | `--script-params` | _(InfluxDB Cloud only)_ Invokable script JSON parameters            | string     |                       |
```

2022-08-02 20:06 UTC, closed without merging

2022-08-02 20:29 UTC, Xenonic commented
Sorry I totally broke my branch with a force push, addressed feedback and fixed the branch here: https://github.com/influxdata/docs-v2/pull/4295