Add TTBR information to Cloud documentation
influxdata/docs-v2 pull request #4307
Opened 2022-08-05 16:01 UTC by sanderson

Closes influxdata/DAR#302

- [x] Rebased/mergeable

2022-08-05 16:03 UTC, philjb requested changes
waiting on this until i get back from holiday

2022-08-05 16:24 UTC, btasker commented on content/influxdb/cloud/reference/internals/ttbr.md
> +The returned 204 status code code does not mean that the point is queryable;
This is a good thing to have in there, might even be worth cross-linking to https://docs.influxdata.com/influxdb/cloud/write-data/troubleshoot/#handle-write-and-delete-responses? That page gives quite a solid overview of the write process and why a write might fail even though it was a 204.

2022-08-05 16:24 UTC, btasker approved these changes
LGTM, thanks!

2022-08-17 19:51 UTC, kelseiv approved these changes

2022-08-23 17:35 UTC, sanderson commented
Still getting pressure for this information from a few directions. I'm going to go ahead and merge this as a stop gap. I think the potential of publishing real-time TTBR numbers is a conversation that needs to happen between Product, Engineering, and SRE.

2022-09-07 15:45 UTC, merged