Oss 2.4 release notes
influxdata/docs-v2 pull request #4352
Opened 2022-08-18 18:13 UTC by lwandzura

Closes #

_Describe your proposed changes here._

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Rebased/mergeable

2022-08-18 19:04 UTC, samhld commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +- Upgrade to [Flux 0.177.0](/flux/v0.x/release-notes/#v01770-2022-08-01).
```suggestion
- Upgrade to [Flux 0.179.0](flux/v0.x/release-notes/#v01790-2022-08-15).
```

2022-08-18 20:01 UTC, kelseiv approved these changes

2022-08-18 20:01 UTC, kelseiv commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +- Deprecate experimental.http.get() and experimental.csv.from().
```suggestion
- Deprecate `experimental.http.get()` and `experimental.csv.from()`.
```

2022-08-18 20:09 UTC, sanderson requested changes

2022-08-18 20:09 UTC, sanderson commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +- Add multiple new join functions to the [`join package`](/flux/v0.x/stdlib/join/), including [join.full()](/flux/v0.x/stdlib/join/full/).
```suggestion
- Add the [`join package`](/flux/v0.x/stdlib/join/) to support inner joins, right outer joins, left outer joins, and full outer joins.
```

2022-08-18 20:09 UTC, sanderson commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +- Add [`initialZero`](/flux/v0.x/stdlib/universe/derivative/#initialzero) parameter to [derivative() function](/flux/v0.x/stdlib/universe/derivative/).
```suggestion
- Add [`initialZero`](/flux/v0.x/stdlib/universe/derivative/#initialzero) parameter to [`derivative()`](/flux/v0.x/stdlib/universe/derivative/).
```

2022-08-18 20:09 UTC, sanderson commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +- Add builtin function `time` to the [`date package`](flux/v0.x/stdlib/date/) to convert `timeable` into `datetime`.
```suggestion
- Add `time()` function to the [`date package`](flux/v0.x/stdlib/date/) to convert timeable types (time and duration) to time types.
```

2022-08-18 20:09 UTC, sanderson commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +  - [http.requests.post()](/flux/v0.x/stdlib/http/requests/post/)
```suggestion
  - [requests.do()](/flux/v0.x/stdlib/http/requests/do/) 
  - [requests.get()](/flux/v0.x/stdlib/http/requests/get/)
  - [requests.peek()](/flux/v0.x/stdlib/http/requests/peek/)
  - [requests.post()](/flux/v0.x/stdlib/http/requests/post/)
```

2022-08-18 20:09 UTC, sanderson commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +- Promote experimental.bitwise into the [`bitwise package`](/flux/v0.x/stdlib/bitwise/).
```suggestion
- Promote `experimental.bitwise()` into the [`bitwise` package](/flux/v0.x/stdlib/bitwise/). 
```

2022-08-18 20:09 UTC, sanderson commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +- Support conditional expressions, constants, and literals in vectorized [map()](flux/v0.x/stdlib/universe/map/).
```suggestion
- Support conditional expressions, constants, and literals in vectorized [`map()`](flux/v0.x/stdlib/universe/map/).
```

2022-08-18 20:09 UTC, sanderson commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +- Optimize [holtWinters() function](/flux/v0.x/stdlib/universe/holtwinters/) and redundant sorts.
```suggestion
- Optimize [`holtWinters()`](/flux/v0.x/stdlib/universe/holtwinters/) and redundant sorts.
```

2022-08-18 20:18 UTC, sanderson requested changes
Sorry, a few more suggestions.

2022-08-18 20:18 UTC, sanderson commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +- Add the [`join package`](/flux/v0.x/stdlib/join/) to support inner joins, right outer joins, left outer joins, and full outer joins.
```suggestion
- Add the [`join` package](/flux/v0.x/stdlib/join/) to support inner joins, right outer joins, left outer joins, and full outer joins.
```

2022-08-18 20:18 UTC, sanderson commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +  - [array.map()](/flux/v0.x/stdlib/array/map/)
```suggestion
  - [`array.concat(`)](/flux/v0.x/stdlib/array/concat/)
  - [`array.filter()`](/flux/v0.x/stdlib/array/filter/)
  - [`array.map()`](/flux/v0.x/stdlib/array/map/)
```

2022-08-18 20:18 UTC, sanderson commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +  - [requests.post()](/flux/v0.x/stdlib/http/requests/post/)
```suggestion
  - [`requests.do()`](/flux/v0.x/stdlib/http/requests/do/) 
  - [`requests.get()`](/flux/v0.x/stdlib/http/requests/get/)
  - [`requests.peek()`](/flux/v0.x/stdlib/http/requests/peek/)
  - [`requests.post()`](/flux/v0.x/stdlib/http/requests/post/)
```

2022-08-18 20:18 UTC, sanderson commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +  - `csv.from()`.
```suggestion
  - `csv.from()`
```

2022-08-18 20:18 UTC, sanderson commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +- Support [InfluxDB 1.x dbrp](/influxdb/v2.4/query-data/influxql/dbrp) names as bucket IDs in `replications` API.
```suggestion
- Support bucket names in the `replications` API and allow [InfluxDB 1.x DBRP](/influxdb/v2.4/query-data/influxql/dbrp) names as bucket names.
```

2022-08-18 20:21 UTC, sanderson approved these changes

2022-08-18 20:26 UTC, sanderson commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +  - [`array.concat(`)](/flux/v0.x/stdlib/array/concat/)
```suggestion
  - [`array.concat()`](/flux/v0.x/stdlib/array/concat/)
```

2022-08-18 20:31 UTC, lwandzura commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +- Add builtin function `time` to the [`date package`](flux/v0.x/stdlib/date/) to convert `timeable` into `datetime`.
@sanderson is it timeable or time.able?

2022-08-18 20:43 UTC, sanderson commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +- Add builtin function `time` to the [`date package`](flux/v0.x/stdlib/date/) to convert `timeable` into `datetime`.
It's "timeable." It describes a type constraint in flux: https://docs.influxdata.com/flux/v0.x/spec/types/#timeable-constraint

These a types that can be cast into a time value.

2022-08-18 20:58 UTC, merged

2023-04-11 15:28 UTC, r00t- commented on content/influxdb/v2.4/reference/release-notes/influxdb.md
> +- Fix error-caching in `bufio.Writer`.
this seems to have ended up here by mistake, no such change was merged for what i can see.
the original [draft](https://github.com/influxdata/docs-v2/issues/4255) references my MR https://github.com/influxdata/influxdb/pull/23127 which has not been merged.
the entry was re-worded to "Fix error-caching in `bufio.Writer`",
but bufio.Writer is part of the go standard library (in which has no related change is to be found.)