port influxql docs into 2.5
influxdata/docs-v2 pull request #4621
Opened 2022-11-07 16:57 UTC by lwandzura

Closes https://github.com/influxdata/docs-v2/issues/3417

moved influxql docs into v2.5. - (note that the branch is still called influxql-2.4)

@gunnaraasen please review the supported/unsupported statements and commands to make sure they are accurate

2022-11-08 19:56 UTC, sanderson requested changes
This review is only partially done. Github stopped loading the PR diff, so I'm submitting as-is and will continue on with more review 🤞🏻 .

2022-11-08 19:56 UTC, sanderson requested changes
This review is only partially done. Github stopped loading the PR diff, so I'm submitting as-is and will continue on with more review 🤞🏻 .

2022-11-10 21:26 UTC, kelseiv approved these changes

2022-11-14 15:04 UTC, lwandzura commented on content/influxdb/v2.4/query-data/influxql/explore-data/select.md
> +`type` can be `float`, `integer`, `string`, or `boolean`.
posted this question in the Edge Team channel

2022-11-14 15:13 UTC, lwandzura commented on content/influxdb/v2.4/query-data/influxql/explore-data/select.md
> +In InfluxDB, queries merge [series](/influxdb/v2.4/reference/glossary/#series) automatically.
not sure what to add here, the explanation depicts what merge behavior is

2022-11-14 15:20 UTC, lwandzura commented on content/influxdb/v2.4/query-data/influxql/explore-data/time-and-timezone.md
> +[`epoch` query string parameter](/influxdb/v2.4/reference/api/influxdb-1x/).
added intro to the doc, moved timezone and updated TOC

2022-11-14 16:18 UTC, lwandzura commented on content/influxdb/v2.4/query-data/influxql/explore-data/regular-expressions.md
> +
I can add at the top and combine with this:

InfluxQL does not support using regular expressions to match
non-string field values in the `WHERE` clause,
[databases](/influxdb/v2.4/reference/glossary/#database), and
[retention policies](/influxdb/v2.4/reference/glossary/#retention-policy-rp).

2022-11-14 17:02 UTC, lwandzura commented on content/influxdb/v2.4/query-data/influxql/explore-data/select.md
> +`type` can be `float`, `integer`, `string`, or `boolean`.
no support, confirmed by David B.  Same as 1.x

2022-11-14 21:41 UTC, sanderson commented on content/influxdb/v2.4/query-data/influxql/explore-data/select.md
> +In InfluxDB, queries merge [series](/influxdb/v2.4/reference/glossary/#series) automatically.
Oh, you're right. The example does explain it. This is fine as-is.

2022-11-16 21:10 UTC, merged