added sql-data-types branch and corresponding doc
influxdata/docs-v2 pull request #4700
Opened 2023-01-13 16:23 UTC by lwandzura

Please review the sql data types doc and let me know what needs to be added and/or removed.

2023-01-13 18:31 UTC, sanderson requested changes

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +  SQL data types
```suggestion
  The InfluxDB SQL implementation supports a number of data types including 64-bit integers,
  double-precision floating point numbers, strings, and more.
```

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +InfluxDB Cloud backed by InfluxDB IOx uses the Apache Arrow DataFusion implementation of SQL. Data types define the type of value that can be stored in table column. In InfluxDB's SQL implementation,
```suggestion
InfluxDB Cloud backed by InfluxDB IOx uses the [Apache Arrow DataFusion](https://arrow.apache.org/datafusion/) implementation of SQL.
Data types define the type of values that can be stored in table columns.
In InfluxDB's SQL implementation, a **measurement** is structured as a table,
and columns are comprised of **tags**, **fields** and **timestamps**. 
```

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +DataFusion uses the Arrow type system for query execution. Data types stored in InfluxDB's storage engine are mapped to SQL data types according to the following tables.
```suggestion
DataFusion uses the Arrow type system for query execution.
Data types stored in InfluxDB's storage engine are mapped to SQL data types at query time. 
```

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +```
~~~suggestion
When performing casting operations, cast to the **name** of the data type, not the actual data type. 
Names are _case-insensitive_. For example:

```sql
SELECT
  '99'::BIGINT, 
  '2019-09-18T00:00:00Z'::timestamp
```
~~~

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +```
~~~suggestion
##### Example character types

```sql
abcdefghijk
time
"h2o_temperature"
```
~~~

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +InfluxDB stores all integers as signed 64bit integers. The following numeric types are supported:
InfluxDB supports both signed and unsigned integers.

```suggestion
The following numeric types are supported:
```

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +| DOUBLE          | FLOAT64   | 64-bit floating-point number |
```suggestion
| BIGINT          | INT64     | 64-bit signed integer        |
| BIGINT UNSIGNED | INT64     | 64-bit unsigned integer      |
| DOUBLE          | FLOAT64   | 64-bit floating-point number |
```

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +Maximum integer: `9223372036854775807`
```suggestion
Minimum signed integer:` -9223372036854775808`  
Maximum signed integer: `9223372036854775807`
```

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +Floats can be a decimal point, decimal integer or decimal fraction.
```suggestion
Floats can be a decimal point, decimal integer, or decimal fraction.
```

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +```
~~~suggestion
##### Example float types

```sql
23.8
-446.89
5.00
0.033
```
~~~

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +
```suggestion
```

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +1566176400
We need to be careful here. These aren't time types. These are integers. You can cast integers to a TIMESTAMP, but they aren't natively recognized as timestamps.

```suggestion
```

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +- float: 0.0 is false, 1.0 is true
```suggestion
- integer: 0 is false, non-zero is true
- uinteger: 0 is false, non-zero is true
- float: 0.0 is false, non-zero is true
```

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +Note that zero vaules are parsed as `false` and non zero negative values are parsed as `true`.
This is redundant with the change above.

```suggestion
```

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +```
~~~suggestion
##### Example boolean types

```sql
true
TRUE
false
FALSE
```
~~~

2023-01-13 18:31 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +- BYTEA
We should probably include all the non-64-bit numeric types that the InfluxDB doesn't support in this list as well.

```suggestion
## Unsupported SQL types

The following SQL types are not currently supported:

- UUID
- BLOB
- CLOB
- BINARY
- VARBINARY
- REGCLASS
- NVARCHAR
- CUSTOM
- ARRAY
- ENUM
- SET
- INTERVAL
- DATETIME
- BYTEA
```

2023-01-17 16:50 UTC, sanderson approved these changes

2023-01-18 16:54 UTC, alamb reviewed
This is sweet -- thank you @lwandzura

2023-01-18 16:59 UTC, sanderson commented on content/influxdb/cloud-iox/sql-data-types.md
> +- INTERVAL
@alamb Thanks for calling this out. Do you know the explicit interval literal formats we support? Are they the same as or similar to those listed [here](https://media.datadirect.com/download/docs/openaccess/alloa/index.html#page/sqlref/interval-literals.html)?

2023-01-19 14:18 UTC, alamb commented on content/influxdb/cloud-iox/sql-data-types.md
> +- INTERVAL
The logical types supported by arrow (and thus by DataFusion) are listed (somewhat obscurely) in https://docs.rs/arrow/31.0.0/arrow/datatypes/index.html

So in this case the interval types are: 

[IntervalDayTimeType](https://docs.rs/arrow/31.0.0/arrow/datatypes/struct.IntervalDayTimeType.html)	A “calendar” interval type in days and milliseconds.
[IntervalMonthDayNanoType](https://docs.rs/arrow/31.0.0/arrow/datatypes/struct.IntervalMonthDayNanoType.html)	A “calendar” interval type in months, days, and nanoseconds.
[IntervalYearMonthType](https://docs.rs/arrow/31.0.0/arrow/datatypes/struct.IntervalYearMonthType.html)	A “calendar” interval type in months.

That is not quite the same as the SQL equivalent. Here are the types when writing about intervals:


```sql
❯ select arrow_typeof(interval '1 month');
+-------------------------------------+
| arrowtypeof(IntervalYearMonth("1")) |
+-------------------------------------+
| Interval(YearMonth)                 |
+-------------------------------------+
1 row in set. Query took 0.006 seconds.
❯ select arrow_typeof(interval '1 second');
+--------------------------------------+
| arrowtypeof(IntervalDayTime("1000")) |
+--------------------------------------+
| Interval(DayTime)                    |
+--------------------------------------+
1 row in set. Query took 0.000 seconds.
```

2023-01-19 15:59 UTC, lwandzura commented on content/influxdb/cloud-iox/sql-data-types.md
> +DataFusion uses the Arrow type system for query execution.
done

2023-01-19 18:08 UTC, lwandzura commented on content/influxdb/cloud-iox/sql-data-types.md
> +- INTERVAL
added interval and examples

2023-01-26 22:52 UTC, merged