Iox time series functions
influxdata/docs-v2 pull request #4752
Opened 2023-02-08 15:32 UTC by lwandzura

Please let me know if I have missed any functions.  I know gapfill is not yet implemented.

2023-02-08 17:07 UTC, sanderson requested changes
A few notes:

- These functions aren't unique to time series, so I'm suggesting we call them "time and date" functions.
- Lets list the functions in alphabetical order
- Include a list of links at the top of the page that links to all the function headings
- There are more time and date functions listed in the DataFusion documentation that are missing here:
  - to_timestamp
  - to_timestamp_millis
  - to_timestamp_micros
  - to_timestamp_seconds
  - extract
  - from_unixtime

2023-02-08 17:07 UTC, sanderson commented on content/influxdb/cloud-iox/reference/sql/functions/time-series.md
> +```
~~~suggestion
```sql
SELECT
  date_part('hour', time) AS hour,
  time,
  "level description", 
  location
FROM h2o_feet
WHERE
  time >= timestamp '2019-08-17T02:54:00Z'
  AND time <= timestamp '2019-08-17T03:06:00Z'
ORDER BY time
```
~~~

2023-02-08 17:07 UTC, sanderson commented on content/influxdb/cloud-iox/reference/sql/functions/time-series.md
> +| 10   | below 3 feet         | santa_monica | 2019-08-17T00:06:00.000Z |
```suggestion
| hour | time                 | level description    | location     |
| :--: | :------------------- | :------------------- | :----------- |
|  2   | 2019-08-17T02:54:00Z | between 3 and 6 feet | coyote_creek |
|  2   | 2019-08-17T02:54:00Z | between 3 and 6 feet | santa_monica |
|  3   | 2019-08-17T03:00:00Z | between 3 and 6 feet | coyote_creek |
|  3   | 2019-08-17T03:00:00Z | between 3 and 6 feet | santa_monica |
|  3   | 2019-08-17T03:06:00Z | between 3 and 6 feet | coyote_creek |
|  3   | 2019-08-17T03:06:00Z | between 3 and 6 feet | santa_monica |
```

2023-02-08 18:17 UTC, alamb commented
Please ping me again when @sanderson 's comments have been addressed. I don't want to end up reviewing content that is rewritten

2023-02-08 18:59 UTC, lwandzura commented
I asked Andrew about some of the temporal functions I left out and while they do work, I am not sure what the use case would be for some, with the exception of extract.  But I can certainly include them.

2023-02-08 22:27 UTC, alamb commented
> I asked Andrew about some of the temporal functions I left out and while they do work, I am not sure what the use case would be for some, with the exception of extract. But I can certainly include them.



I agree `extract ` has a usecase.

2023-02-13 15:56 UTC, lwandzura commented
@alamb I am a little confused on the to_timestamp function usage

This works:

SELECT to_timestamp(time) 
FROM cpu 
LIMIT 1

However, the format in Datafusion's docs state this should work and I am getting errors:

basic syntax:  to_timestamp(timestamp, format)


SELECT TO_TIMESTAMP('2023-01-01 08:50:10', 'YYYY-MM-DD')
FROM h2o_feet

SELECT TO_TIMESTAMP('2020-01-31T09:26:56.123Z', 'YYYY-MM-DD')
FROM h2o_feet

Am I on the wrong track here?

2023-02-13 19:05 UTC, alamb commented
Hi @lwandzura 

> However, the format in Datafusion's docs state this should work and I am getting errors:
> basic syntax: to_timestamp(timestamp, format)

The docs I can find don't refer to the second argument (though they are also not very helpful in general):
https://arrow.apache.org/datafusion/user-guide/expressions.html#temporal-expressions

I don't think the to_timestamp function supports a second argument currently in DataFusion -- can you copy the exact error you are seeing?

2023-02-13 19:07 UTC, alamb commented
When I run this I see

```
❯ SELECT TO_TIMESTAMP('2020-01-31T09:26:56.123Z', 'YYYY-MM-DD');
Plan("Coercion from [Utf8, Utf8] to the signature Uniform(1, [Int64, Timestamp(Nanosecond, None), Timestamp(Microsecond, None), Timestamp(Millisecond, None), Timestamp(Second, None), Utf8]) failed.")
❯
```

Which says to me that the function requires a single argument of one of the type in that list (which is a pretty bad message)

2023-02-14 18:09 UTC, sanderson requested changes

2023-02-14 20:07 UTC, merged