Vale linter config
influxdata/docs-v2 pull request #5060
Opened 2023-07-28 19:13 UTC by jstirnaman

Initial commit of Vale linter config for spelling and grammar. This is still WIP, but helpful enough to start using and refining in local environments.

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Rebased/mergeable

2023-07-28 19:15 UTC, jstirnaman commented on content/influxdb/cloud-dedicated/.vale.ini
> +Google.Headings.Capitalization = NO
```suggestion
Google.Headings = NO
```

2023-07-28 19:15 UTC, jstirnaman commented on content/influxdb/cloud-serverless/.vale.ini
> +Google.Headings.Capitalization = NO
```suggestion
Google.Headings = NO
```

2023-07-31 14:30 UTC, sanderson requested changes
Very cool. Some questions and suggestions. How deep in the hole are we after running the linter? 😄

2023-07-31 14:30 UTC, sanderson commented on .ci/vale/styles/Vocab/Cloud-Serverless/reject.txt
> +database name
```suggestion
We need to decide how to handle this with DBRP mapping and people coming from 1.x to serverless.
```

2023-07-31 21:42 UTC, jstirnaman commented on .ci/vale/styles/Google/WordList.yml
> +  CLI: command-line tool
> I think this is going to get really annoying 😄. I don't know that I want to replace every instance of "CLI" with "command-line tool."

I thought exactly the same thing

2023-07-31 21:45 UTC, jstirnaman commented on .ci/vale/styles/Google/WordList.yml
> +  Cloud: Google Cloud Platform|GCP
> Vendor-specific. We need to remove this one.
Yeah, that def generates a lot of noise.

2023-07-31 21:51 UTC, jstirnaman commented on .ci/vale/styles/Google/DateFormat.yml
> +tokens:
We can disable the rule, though honestly I didn't see it throw. Appears to check for non-U.S. date formats (`12-Jan-2023` or `12-01-2023`)

2023-07-31 21:53 UTC, jstirnaman commented on .ci/vale/styles/Google/Headings.yml
> +exceptions:
Yeah or create our own to use additionally

2023-07-31 21:56 UTC, jstirnaman commented on .ci/vale/styles/Google/WordList.yml
> +  k8s: Kubernetes
The Vocab `accept.txt` files are preferred words that override these, IIUC.

2023-07-31 22:43 UTC, sanderson approved these changes

2023-07-31 22:43 UTC, sanderson commented on .ci/vale/styles/Google/DateFormat.yml
> +tokens:
Cool. Just wanted to double check.

2023-08-01 15:38 UTC, merged