Telegraf: fix Windows install instructions.
influxdata/docs-v2 pull request #5086
Opened 2023-08-14 23:18 UTC by jstirnaman

Closes #4935

For details, see original #4935

2023-08-14 23:27 UTC, sanderson requested changes
Looks good. Just some minor suggestions.

2023-08-14 23:27 UTC, sanderson commented on content/telegraf/v1.26/install.md
> +Run one of the following commands to start Telegraf collecting and processing metrics:
```suggestion
Run one of the following commands to start Telegraf and begin collecting and processing metrics:
```

2023-08-14 23:27 UTC, sanderson commented on content/telegraf/v1.26/install.md
> +To start Telegraf as a service now:
```suggestion
Start Telegraf as a launchd service:
```

2023-08-14 23:27 UTC, sanderson commented on content/telegraf/v1.26/install.md
> +    > The remaining instructions assume that `telegraf.exe` and `telegraf.conf` files are stored in `C:\Program Files\InfluxData\telegraf` or that you created a Symlink to point to this directory.
```suggestion
    {{% note %}}
The remaining instructions assume that `telegraf.exe` and `telegraf.conf` files are stored in
`C:\Program Files\InfluxData\telegraf` or that you created a Symlink to point to this directory.
    {{% /note %}}
```

2023-08-14 23:27 UTC, sanderson commented on content/telegraf/v1.26/install.md
> +3.  Optional: Disable the [`inputs.processes` plugin](/{{% latest "telegraf" %}}/plugins/#input-processes).
```suggestion
3.  _(Optional)_ Disable the [`inputs.processes` plugin](/telegraf/v1.26/plugins/#input-processes).
```

2023-08-14 23:27 UTC, sanderson commented on content/telegraf/v1.26/install.md
> +4.  Optional: Enable a plugin to collect Windows-specific metrics--for example, uncomment the [`inputs.win_services`  plugin](/{{% latest "telegraf" %}}/plugins/#input-win_services) configuration lin
```suggestion
4.  _(Optional)_ Enable a plugin to collect Windows-specific metrics--for example, uncomment the [`inputs.win_services`  plugin](/telegraf/v1.26/plugins/#input-win_services) configuration line:
```

2023-08-14 23:27 UTC, sanderson commented on content/telegraf/v1.27/install.md
> +Run one of the following commands to start Telegraf collecting and processing metrics:
```suggestion
Run one of the following commands to start Telegraf and begin collecting and processing metrics:
```

2023-08-14 23:27 UTC, sanderson commented on content/telegraf/v1.27/install.md
> +To start Telegraf as a service now:
```suggestion
Start Telegraf as a launchd service:
```

2023-08-14 23:27 UTC, sanderson commented on content/telegraf/v1.27/install.md
> +    > The remaining instructions assume that `telegraf.exe` and `telegraf.conf` files are stored in `C:\Program Files\InfluxData\telegraf` or that you created a Symlink to point to this directory.
```suggestion
    {{% note %}}
The remaining instructions assume that `telegraf.exe` and `telegraf.conf` files are stored in
`C:\Program Files\InfluxData\telegraf` or that you created a Symlink to point to this directory.
    {{% /note %}}
```

2023-08-14 23:27 UTC, sanderson commented on content/telegraf/v1.27/install.md
> +3.  Optional: Disable the [`inputs.processes` plugin](/{{% latest "telegraf" %}}/plugins/#input-processes).
```suggestion
3.  _(Optional)_ Disable the [`inputs.processes` plugin](/{{% latest "telegraf" %}}/plugins/#input-processes).
```

2023-08-14 23:27 UTC, sanderson commented on content/telegraf/v1.27/install.md
> +4.  Optional: Enable a plugin to collect Windows-specific metrics--for example, uncomment the [`inputs.win_services`  plugin](/{{% latest "telegraf" %}}/plugins/#input-win_services) configuration lin
```suggestion
4.  _(Optional)_ Enable a plugin to collect Windows-specific metrics--for example, uncomment the [`inputs.win_services`  plugin](/{{% latest "telegraf" %}}/plugins/#input-win_services) configuration line:
```

2023-08-15 14:14 UTC, jstirnaman commented on content/telegraf/v1.26/install.md
> +3.  Optional: Disable the [`inputs.processes` plugin](/{{% latest "telegraf" %}}/plugins/#input-processes).
https://developers.google.com/style/procedures#optional-steps

2023-08-15 15:13 UTC, merged