Execute queries reorg
influxdata/docs-v2 pull request #5100
Opened 2023-08-23 23:00 UTC by jstirnaman

Merges SQL > Execute queries, InfluxQL > Execute queries into Query data > Execute queries.
Merges InfluxQL examples into pages with SQL examples.
Updates all client library class names, params, and signatures to reflect the latest releases.
Removes pandas from Use Python and adds more PyArrow examples without additional dependencies.
Adds note to recommend client libraries over Flight clients.
Miscellaneous fixes.
Adds a starter git pre-commit hook for Vale. Not sure it works correctly yet. To use it, copy the file into .git/hooks as `pre-commit` (without an extension).

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Rebased/mergeable

2023-08-23 23:04 UTC, jstirnaman commented on content/influxdb/cloud-serverless/query-data/execute-queries/influxdb-v1-api.md
> +  the name of the [database (bucket)](/influxdb/cloud-serverless/admin/buckets/) to query.
```suggestion
  the name of the [database (bucket)](/influxdb/cloud-serverless/admin/buckets/) to query
```

2023-08-24 16:44 UTC, sanderson requested changes
Looks good. Thanks for doing this. Just some suggestions.

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-dedicated/query-data/execute-queries/client-libraries/go.md
> +        Host:       "https://cluster-id.influxdb.io",
```suggestion
        Host:       "https://{{< influxdb/host >}}",
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-dedicated/query-data/execute-queries/client-libraries/go.md
> +        Host:       "https://cluster-id.influxdb.io",
```suggestion
        Host:       "https://{{< influxdb/host >}}",
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-dedicated/query-data/execute-queries/client-libraries/python.md
> +title: Use Python and SQL or InfluxQL to query data
```suggestion
title: Use Python to query data
seotitle: Use Python and SQL or InfluxQL to query data
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-dedicated/query-data/execute-queries/influxdb-v1-api.md
>  curl --get https://cluster-id.influxdb.io/query \
```suggestion
curl --get https://{{< influxdb/host >}}/query \
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-dedicated/reference/client-libraries/flight/csharp-flight.md
> +[InfluxDB v3 client libraries](/influxdb/cloud-dedicated/reference/client-libraries/v3/) client libraries wrap Apache Arrow Flight clients
```suggestion
[InfluxDB v3 client libraries](/influxdb/cloud-dedicated/reference/client-libraries/v3/) wrap Apache Arrow Flight clients
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-dedicated/reference/client-libraries/flight/go-flight.md
> +[InfluxDB v3 client libraries](/influxdb/cloud-dedicated/reference/client-libraries/v3/) client libraries wrap Apache Arrow Flight clients
```suggestion
[InfluxDB v3 client libraries](/influxdb/cloud-dedicated/reference/client-libraries/v3/) wrap Apache Arrow Flight clients
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-dedicated/reference/client-libraries/flight/java-flightsql.md
> +    <!-- Can't make filesystem-diagram shortcode indent properly -->
Hugo hates shortcodes in nested lists 🤷🏻‍♂️

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-serverless/get-started/query.md
> +        Host:     "https://cloud2.influxdata.com",
```suggestion
        Host:     "https://{{< influxdb/host >}}",
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-serverless/query-data/execute-queries/client-libraries/go.md
> +title: Use Go and SQL or InfluxQL to query data
```suggestion
title: Use Go to query data
seotitle: Use Go and SQL or InfluxQL to query data
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-serverless/query-data/execute-queries/client-libraries/go.md
> +            Host:       "https://cluster-id.influxdb.io",
```suggestion
            Host:       "https://cloud2.influxdata.com",
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-serverless/query-data/execute-queries/client-libraries/go.md
> +        Host:       "https://cloud2.influxdata.com",
```suggestion
        Host:       "https://{{< influxdb/host >}}",
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-serverless/query-data/execute-queries/client-libraries/python.md
> +title: Use Python and SQL or InfluxQL to query data
```suggestion
title: Use Python to query data
seotitle: Use Python and SQL or InfluxQL to query data
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-serverless/query-data/execute-queries/client-libraries/python.md
>      host='cloud2.influxdata.com',
```suggestion
    host='{{< influxdb/host >}}',
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-serverless/query-data/execute-queries/client-libraries/python.md
>      host='cloud2.influxdata.com',
```suggestion
    host='{{< influxdb/host >}}',
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-serverless/query-data/execute-queries/client-libraries/python.md
> +    host='cluster-id.influxdb.io',
```suggestion
    host='{{< influxdb/host >}}',
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-serverless/reference/client-libraries/flight/go-flight.md
> +[InfluxDB v3 client libraries](/influxdb/cloud-serverless/reference/client-libraries/v3/) client libraries wrap Apache Arrow Flight clients
```suggestion
[InfluxDB v3 client libraries](/influxdb/cloud-serverless/reference/client-libraries/v3/) wrap Apache Arrow Flight clients
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-serverless/reference/client-libraries/flight/java-flightsql.md
> +[InfluxDB v3 client libraries](/influxdb/cloud-serverless/reference/client-libraries/v3/) client libraries wrap Apache Arrow Flight clients
```suggestion
[InfluxDB v3 client libraries](/influxdb/cloud-serverless/reference/client-libraries/v3/) wrap Apache Arrow Flight clients
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-serverless/reference/client-libraries/flight/python-flight.md
> +[InfluxDB v3 client libraries](/influxdb/cloud-serverless/reference/client-libraries/v3/) client libraries wrap Apache Arrow Flight clients
```suggestion
[InfluxDB v3 client libraries](/influxdb/cloud-serverless/reference/client-libraries/v3/) wrap Apache Arrow Flight clients
```

2023-08-24 16:44 UTC, sanderson commented on content/influxdb/cloud-serverless/reference/client-libraries/v3/go.md
> +        Host:       "https://cloud2.influxdata.com",
```suggestion
        Host:       "https://{{< influxdb/host >}}",
```

2023-08-24 18:38 UTC, jstirnaman commented on content/influxdb/cloud-dedicated/get-started/query.md
> +            "https://cluster-id.influxdb.io", token: token, database: database);
Oh, I didn't know you merged that. I meant to go look.

2023-08-24 18:43 UTC, sanderson commented on content/influxdb/cloud-dedicated/get-started/query.md
> +            "https://cluster-id.influxdb.io", token: token, database: database);
Oh shoot. I thought I had, but I haven't. One sec...

2023-08-24 18:49 UTC, jstirnaman commented on content/influxdb/cloud-dedicated/reference/client-libraries/flight/python-flightsql-dbapi.md
>  [InfluxDB v3 client libraries](/influxdb/cloud-dedicated/reference/client-libraries/v3/) client libraries wrap Apache Arrow Flight clients
```suggestion
[InfluxDB v3 client libraries](/influxdb/cloud-dedicated/reference/client-libraries/v3/) wrap Apache Arrow Flight clients
```

2023-08-24 18:49 UTC, jstirnaman commented on content/influxdb/cloud-serverless/reference/client-libraries/flight/python-flightsql-dbapi.md
>  [InfluxDB v3 client libraries](/influxdb/cloud-serverless/reference/client-libraries/v3/) client libraries wrap Apache Arrow Flight clients
```suggestion
[InfluxDB v3 client libraries](/influxdb/cloud-serverless/reference/client-libraries/v3/) wrap Apache Arrow Flight clients
```

2023-08-24 20:11 UTC, merged