5143-Add Optimize Queries page with query analysis help
influxdata/docs-v2 pull request #5165
Opened 2023-10-03 21:51 UTC by jstirnaman

- Closes Client library query traces: Python https://github.com/influxdata/docs-v2/issues/5143
- Dedicated and Clustered examples for enabling query tracing and extracting headers
- System.queries table
- Explain and Analyze
- For now, skip tests for sample Flight responses until we add in code samples.

**Don't merge** until Python client library allows for setting query request headers (https://github.com/InfluxCommunity/influxdb3-python/pull/64)

2023-10-03 21:55 UTC, jstirnaman commented
I'd appreciate you fact-checking me on `optimize-queries.md` for Dedicated, Clustered, and Serverless.

2023-10-03 23:34 UTC, sanderson requested changes
Looks good. Just some minor suggestions.

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/cloud-dedicated/query-data/execute-queries/optimize-queries.md
> +<!-- /TOC -->
```suggestion
Use the following tools to help you identify performance bottlenecks and troubleshoot problems in queries:

<!-- TOC -->

- [EXPLAIN and ANALYZE](#explain-and-analyze)
- [Enable trace logging](#enable-trace-logging)
  - [Extract a trace ID](#extract-a-trace-id)
- [Retrieve system information](#retrieve-system-information)
  - [Retrieve query instance information](#retrieve-query-instance-information)

<!-- /TOC -->
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/cloud-dedicated/query-data/execute-queries/optimize-queries.md
> +### EXPLAIN and ANALYZE
```suggestion
## EXPLAIN and ANALYZE
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/cloud-dedicated/query-data/execute-queries/optimize-queries.md
> +To view the query engine's execution plan and metrics for an SQL query, prepend [`EXPLAIN`](/influxdb/cloud-dedicated/reference/sql/explain/) or [`EXPLAIN ANALYZE`](/influxdb/cloud-dedicated/referenc
This is true for both SQL and InfluxQL.

```suggestion
To view the query engine's execution plan and metrics for an SQL or InfluxQL query, prepend [`EXPLAIN`](/influxdb/cloud-dedicated/reference/sql/explain/) or [`EXPLAIN ANALYZE`](/influxdb/cloud-dedicated/reference/sql/explain/#explain-analyze) to the query.
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/cloud-dedicated/query-data/execute-queries/optimize-queries.md
> +The output is similar to the following:
There may be differences in the output between SQL and InfluxQL. Maybe some tabs here?

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/cloud-dedicated/query-data/execute-queries/optimize-queries.md
> +### Enable trace logging
```suggestion
## Enable trace logging
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/cloud-dedicated/query-data/execute-queries/optimize-queries.md
> +#### Extract a trace ID
```suggestion
### Extract a trace ID
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/cloud-dedicated/query-data/execute-queries/optimize-queries.md
> +### Retrieve system information
```suggestion
## Retrieve system information
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/cloud-dedicated/query-data/execute-queries/optimize-queries.md
> +#### Retrieve query instance information
```suggestion
### Retrieve query instance information
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/cloud-dedicated/query-data/execute-queries/optimize-queries.md
> +To enable the feature and query `system.queries`, include an `"iox-debug"` header set to `"true"` and use SQL to query the table
```suggestion
To enable the feature and query `system.queries`, include an `"iox-debug"` header set to `"true"` and use SQL to query the table.
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/cloud-serverless/query-data/execute-queries/optimize-queries.md
> +<!-- /TOC -->
```suggestion
Use the following tools to help you identify performance bottlenecks and troubleshoot problems in queries:

<!-- TOC -->

- [EXPLAIN and ANALYZE](#explain-and-analyze)
- [Enable trace logging](#enable-trace-logging)

<!-- /TOC -->
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/cloud-serverless/query-data/execute-queries/optimize-queries.md
> +### EXPLAIN and ANALYZE
```suggestion
## EXPLAIN and ANALYZE
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/cloud-serverless/query-data/execute-queries/optimize-queries.md
> +To view the query engine's execution plan and metrics for an SQL query, prepend [`EXPLAIN`](/influxdb/cloud-serverless/reference/sql/explain/) or [`EXPLAIN ANALYZE`](/influxdb/cloud-serverless/refere
```suggestion
To view the query engine's execution plan and metrics for an SQL or InfluxQL query, prepend [`EXPLAIN`](/influxdb/cloud-serverless/reference/sql/explain/) or [`EXPLAIN ANALYZE`](/influxdb/cloud-serverless/reference/sql/explain/#explain-analyze) to the query.
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/cloud-serverless/query-data/execute-queries/optimize-queries.md
> +### Enable trace logging
```suggestion
## Enable trace logging
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/clustered/query-data/execute-queries/optimize-queries.md
> +<!-- /TOC -->
```suggestion
Use the following tools to help you identify performance bottlenecks and troubleshoot problems in queries:

<!-- TOC -->

- [EXPLAIN and ANALYZE](#explain-and-analyze)
- [Enable trace logging](#enable-trace-logging)
  - [Extract a trace ID](#extract-a-trace-id)
- [Retrieve system information](#retrieve-system-information)
  - [Retrieve query instance information](#retrieve-query-instance-information)

<!-- /TOC -->
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/clustered/query-data/execute-queries/optimize-queries.md
> +### EXPLAIN and ANALYZE
```suggestion
## EXPLAIN and ANALYZE
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/clustered/query-data/execute-queries/optimize-queries.md
> +To view the query engine's execution plan and metrics for an SQL query, prepend [`EXPLAIN`](/influxdb/clustered/reference/sql/explain/) or [`EXPLAIN ANALYZE`](/influxdb/clustered/reference/sql/explai
```suggestion
To view the query engine's execution plan and metrics for an SQL or InfluxQL query, prepend [`EXPLAIN`](/influxdb/clustered/reference/sql/explain/) or [`EXPLAIN ANALYZE`](/influxdb/clustered/reference/sql/explain/#explain-analyze) to the query.
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/clustered/query-data/execute-queries/optimize-queries.md
> +### Enable trace logging
```suggestion
## Enable trace logging
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/clustered/query-data/execute-queries/optimize-queries.md
> +#### Extract a trace ID
```suggestion
### Extract a trace ID
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/clustered/query-data/execute-queries/optimize-queries.md
> +### Retrieve system information
```suggestion
## Retrieve system information
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/clustered/query-data/execute-queries/optimize-queries.md
> +#### Retrieve query instance information
```suggestion
### Retrieve query instance information
```

2023-10-03 23:34 UTC, sanderson commented on content/influxdb/clustered/query-data/execute-queries/optimize-queries.md
> +To enable the feature and query `system.queries`, include an `"iox-debug"` header set to `"true"` and use SQL to query the table
```suggestion
To enable the feature and query `system.queries`, include an `"iox-debug"` header set to `"true"` and use SQL to query the table.
```

2023-10-04 08:04 UTC, btasker approved these changes

2023-10-04 08:04 UTC, btasker commented on content/influxdb/clustered/query-data/execute-queries/optimize-queries.md
> +InfluxDB Support can then use the ID you provide and the associated trace ID to filter and correlate related log entries for the query.
This probably needs tweaking for Clustered. I *assume* Clustered still has the bits for tracing, but it wouldn't be Support retrieving it (unless the traces are being sent offsite?).

If Clustered definitely supports tracing, the wording is probably "InfluxDB Support can then help you use the ID..."

2023-10-04 08:04 UTC, btasker commented on content/influxdb/cloud-dedicated/query-data/execute-queries/optimize-queries.md
> +The tracing system follows the [OpenTelemetry traces](https://opentelemetry.io/docs/concepts/signals/traces/) model for providing observability into a request.
Probably worth noting somewhere that adding trace headers to all queries, all the time, is not recommended.

2023-10-04 08:45 UTC, crepererum commented on content/influxdb/cloud-serverless/query-data/execute-queries/optimize-queries.md
> +  df = pd.concat([df, table.to_pandas()])
The information shown by `EXPLAIN ANALYZE` should be a superset of a plain `EXPLAIN` query. There's no need to combine both. Either use one or the other.

2023-10-16 19:48 UTC, sanderson approved these changes

2023-10-16 20:08 UTC, merged