docs(clustered): add gcp policy
influxdata/docs-v2 pull request #5296
Opened 2024-01-10 10:15 UTC by jdockerty

Closes https://github.com/influxdata/project-clustered/issues/217

This provides the required storage policy for InfluxDB 3 to manage its access to the configured object store, GCS in this case.

This role is a managed role, offered by GCP directly, so can simply be attached to an existing principal.

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Rebased/mergeable

2024-01-10 16:24 UTC, sanderson requested changes
Looks good. Just some stylistic suggestions.

2024-01-10 16:24 UTC, sanderson commented on content/influxdb/clustered/install/prerequisites.md
> +For example, when leveraging Google Service Accounts:
```suggestion
To use Google Cloud Storage (GCS) as your object store, your [AIM principal](https://cloud.google.com/iam/docs/overview)
should be granted the `roles/storage.objectUser` role.

For example, if using [Google Service Accounts](https://cloud.google.com/iam/docs/service-account-overview):
```

2024-01-10 16:24 UTC, sanderson commented on content/influxdb/clustered/install/prerequisites.md
> +- {{% code-placeholder-key %}}`GCP_BUCKET`{{% /code-placeholder-key %}}: The name of your GCS bucket.
```suggestion
- {{% code-placeholder-key %}}`GCP_SERVICE_ACCOUNT`{{% /code-placeholder-key %}}: Google Service Account name
- {{% code-placeholder-key %}}`GCP_BUCKET`{{% /code-placeholder-key %}}: GCS bucket name
```

2024-01-10 16:24 UTC, sanderson commented on content/influxdb/clustered/install/prerequisites.md
> +This is a built-in role for Azure which encompasses common permissions, you can assign it by issuing the following command:
```suggestion
To use Azure Blob Storage as your object store, your [service principal](https://learn.microsoft.com/en-us/entra/architecture/service-accounts-principal)
should be granted the `Storage Blob Data Contributor` role.
This is a built-in role for Azure which encompasses common permissions.
You can assign it using the following command:
```

2024-01-10 16:24 UTC, sanderson commented on content/influxdb/clustered/install/prerequisites.md
> +- {{% code-placeholder-key %}}`AZURE_STORAGE_CONTAINER`{{% /code-placeholder-key %}}: The name of the container within your Azure Blob storage account.
```suggestion
- {{% code-placeholder-key %}}`PRINCIPAL`{{% /code-placeholder-key %}}: A user, group, or service principal that the role should be assigned to
- {{% code-placeholder-key %}}`AZURE_SUBSCRIPTION`{{% /code-placeholder-key %}}: Your Azure subscription
- {{% code-placeholder-key %}}`AZURE_RESOURCE_GROUP`{{% /code-placeholder-key %}}: The resource group that your Azure Blob storage account belongs to.
- {{% code-placeholder-key %}}`AZURE_STORAGE_ACCOUNT`{{% /code-placeholder-key %}}: Azure Blob storage account name
- {{% code-placeholder-key %}}`AZURE_STORAGE_CONTAINER`{{% /code-placeholder-key %}}: Container name in your Azure Blob storage account
```

2024-01-10 17:03 UTC, jdockerty commented
@sanderson Changes have been made based on feedback, PTAL :100:

2024-01-16 16:08 UTC, sanderson commented on content/influxdb/clustered/install/prerequisites.md
> +- {{% code-placeholder-key %}}`AZURE_RESOURCE_GROUP`{{% /code-placeholder-key %}}: The resource group that your Azure Blob storage account belongs to.
```suggestion
- {{% code-placeholder-key %}}`AZURE_RESOURCE_GROUP`{{% /code-placeholder-key %}}: The resource group that your Azure Blob storage account belongs to
```

2024-01-16 16:10 UTC, merged