Updated grafana.md to include the new InfluxDB data source SQL setup
influxdata/docs-v2 pull request #5307
Opened 2024-01-22 17:21 UTC by Jayclifford345

Draft for proposed Grafana changes. 

- [x] Serverless
- [x] Dedicated
- [x] Clustered

---

- [x] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [x] Rebased/mergeable

2024-01-31 22:25 UTC, jstirnaman requested changes
Some minor fixes

2024-01-31 22:25 UTC, jstirnaman commented on content/influxdb/cloud-serverless/process-data/visualize/grafana.md
> +    - **Database**: Provide a database name to query. Use the database name that is mapped to your InfluxBD Cloud bucket.
```suggestion
    - **Database**: Provide a database name to query. Use the database name that is mapped to your InfluxDB Cloud bucket.
```

2024-01-31 22:25 UTC, jstirnaman commented on content/influxdb/cloud-serverless/process-data/visualize/grafana.md
> +
```suggestion
    - **HTTP Method**: Choose one of the available HTTP request methods to use when querying data:

```

2024-02-01 23:29 UTC, sanderson commented
I'm holding off on the v1-v2 changes for another branch. I think it's better to get the v3 stuff out there.

2024-02-05 16:34 UTC, merged