Clustered installation docs
influxdata/docs-v2 pull request #5327
Opened 2024-02-16 15:05 UTC by sanderson

Adds installation and configuration docs to InfluxDB Clustered.

@jstirnaman most of these changes were reviewed before being merged into the `clustered-install` branch, so it's likely good to go, but it may benefit from a quick once-over.

- [x] Rebased/mergeable

2024-02-16 21:39 UTC, jstirnaman requested changes
TIL!

2024-02-16 21:39 UTC, jstirnaman commented on content/influxdb/clustered/install/configure-cluster.md
> +Finally, you will need to add all the users you wish to have access to use influxctl.
```suggestion
Finally, add all the users you wish to have access to use `influxctl`.
```

2024-02-16 21:39 UTC, jstirnaman commented on content/influxdb/clustered/install/configure-cluster.md
> +See [Adding or removing users](/repalce/this) for more details.
```suggestion
See [Adding or removing users](/influxdb/clustered/admin/users/) for more details.
```

I assume?

2024-02-20 15:30 UTC, sanderson commented on content/influxdb/clustered/install/auth.md
> +{{% /tab-content %}}
Ah, this was meant as placeholder and should've been commented out. Thanks for catching. I'll ping the clustered team to see if they can provide instructions on using Auth0.

2024-02-20 15:30 UTC, sanderson commented on content/influxdb/clustered/install/configure-cluster.md
> +- **`influxdb-docker-config.json`**: Authenticated Docker configuration file.
I believe it's controlled by an auth token. As I understand it, we provide the customer with a Docker config with pre-populated settings, including a token or some type of auth to pull the private images required to provision a cluster.

2024-02-20 15:30 UTC, sanderson commented on content/influxdb/clustered/install/configure-cluster.md
> +  - `storage`: Storage size. We recommend a minimum of 2 gibibytes (`2Gi`).
Yes, this format is specific to the config: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#meaning-of-memory

2024-02-20 15:30 UTC, sanderson commented on content/influxdb/clustered/install/prerequisites.md
> +The recommended minimum size of the local storage is 2 gibibytes (`2Gi`).
Yep, specific to Kubernetes configurations and defining resources available to pods.

2024-02-20 19:56 UTC, merged