Manage users in InfluxDB Clustered
influxdata/docs-v2 pull request #5555
Opened 2024-08-05 23:06 UTC by sanderson

Related to https://github.com/influxdata/DAR/issues/436

- [x] Rebased/mergeable

2024-08-05 23:22 UTC, jenniferplusplus approved these changes

2024-08-06 14:26 UTC, jstirnaman requested changes
Looks good. Just a few suggestions.

2024-08-06 14:26 UTC, jstirnaman commented on content/influxdb/clustered/admin/users/_index.md
> +cluster. One does not need to be a users to read and write data in your cluster,
```suggestion
cluster. A person or client doesn't need to be a user to read and write data in your cluster,
```

2024-08-06 14:26 UTC, jstirnaman commented on content/influxdb/clustered/admin/users/add.md
> +2.  Add the newly added user to your InfluxDB `AppInstance` resource.
```suggestion
2.  Add the user to your InfluxDB `AppInstance` resource.
```

2024-08-06 14:26 UTC, jstirnaman commented on content/influxdb/clustered/admin/users/add.md
> +<!--pytest.mark.skip-->
```suggestion
```
It's only necessary to skip executables (`bash`, `sh`, `python`)

2024-08-06 14:26 UTC, jstirnaman commented on content/influxdb/clustered/admin/users/add.md
> +  # The identity provider to be used e.g. "keycloak", "auth0", "azure", etc
```suggestion
  # The identity provider to be used (such as "keycloak", "auth0", or "azure")
```

2024-08-06 14:26 UTC, jstirnaman commented on content/influxdb/clustered/admin/users/add.md
> +  # Note for Azure Active Directory it must be exactly "azure"
```suggestion
  # Note, use "azure" for Azure Active Directory
```

2024-08-06 14:26 UTC, jstirnaman commented on content/influxdb/clustered/admin/users/add.md
> +
```suggestion
```

Not needed.

2024-08-06 14:26 UTC, jstirnaman commented on content/influxdb/clustered/admin/users/add.md
> +
```suggestion
```

2024-08-06 14:26 UTC, jstirnaman commented on content/influxdb/clustered/admin/users/add.md
> +  # Note for Azure Active Directory it must be exactly "azure"
```suggestion
  # Note, use "azure" for Azure Active Directory.
```

2024-08-06 14:26 UTC, jstirnaman commented on content/influxdb/clustered/admin/users/add.md
> +  # Note for Azure Active Directory it must be exactly "azure"
```suggestion
  # Note, use "azure" for Azure Active Directory.
```

2024-08-06 14:26 UTC, jstirnaman commented on content/influxdb/clustered/admin/users/remove.md
> +1.  Remove or disable the user in your identity provider.
```suggestion
1.  Remove or deactivate the user in your identity provider.
```

2024-08-06 14:26 UTC, jstirnaman commented on content/influxdb/clustered/admin/users/remove.md
> +
```suggestion
```

2024-08-06 14:26 UTC, jstirnaman commented on content/influxdb/clustered/admin/users/remove.md
> +
```suggestion
```

2024-08-06 14:26 UTC, jstirnaman commented on content/influxdb/clustered/admin/users/remove.md
> +your `AppInstance` resource.
```suggestion
access to your InfluxDB cluster.
However, you should still remove them from your `AppInstance` resource.
```

2024-08-06 14:26 UTC, jstirnaman commented on content/influxdb/clustered/install/configure-cluster/use-helm.md
>  Finally, add all the users you wish to have access to use `influxctl`.
```suggestion
Finally, add the users you wish to have access to use `influxctl`.
```

2024-08-06 14:26 UTC, jstirnaman commented on content/influxdb/clustered/install/configure-cluster/use-helm.md
>  Update the `admin.users` field with a list of these users.
```suggestion
Update the `admin.users` field with a list of the users.
```

2024-08-06 20:10 UTC, jstirnaman approved these changes
👍

2024-08-06 20:26 UTC, merged