doc(serverless): add workaround for return data that is array/list
influxdata/docs-v2 pull request #5570
Opened 2024-08-19 22:51 UTC by appletreeisyellow

Closes https://github.com/influxdata/idpe/issues/18775

_Describe your proposed changes here._

- [x] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [x] Rebased/mergeable

2024-08-19 23:01 UTC, sanderson requested changes

2024-08-19 23:01 UTC, sanderson commented on content/influxdb/cloud-serverless/query-data/troubleshoot-and-optimize/troubleshoot.md
> +- The query return type is not supported by the client library. For example, array / list type may not be supported, in this case convert the result into a string using `array_to_string()`. For examp
```suggestion
- The query return type is not supported by the client library.
  For example, array or list types may not be supported.
  In this case, use `array_to_string()` to convert the array value to a string--for example:
```

2024-08-19 23:01 UTC, sanderson commented on content/influxdb/cloud-serverless/query-data/troubleshoot-and-optimize/troubleshoot.md
> +{{% /code-tab-content %}}
~~~suggestion
```sql
SELECT array_to_string(array_agg([1, 2, 3]), ', ')
```
~~~

2024-08-20 14:49 UTC, sanderson approved these changes
Thanks @appletreeisyellow! This is good to go!

2024-08-20 14:49 UTC, appletreeisyellow commented
Thank you @sanderson!

2024-08-20 14:54 UTC, merged