Clustered: simplify public pull secrets
influxdata/docs-v2 pull request #5572
Opened 2024-08-20 17:19 UTC by jenniferplusplus

Crane is not actually required when using the InfluxData public image registry. It seems like referring to it before the public/private branch in the docs can cause some confusion. This moves all of the crane steps into the private branch, where it's needed.

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Rebased/mergeable

2024-08-20 19:19 UTC, jstirnaman requested changes
A few small changes

2024-08-20 19:19 UTC, jstirnaman commented on content/influxdb/clustered/install/configure-cluster/directly.md
> +In both scenarios, you need a valid pull secret.
```suggestion
In both scenarios, you need a valid _pull secret_.
```

2024-08-20 19:19 UTC, jstirnaman commented on content/influxdb/clustered/install/configure-cluster/directly.md
>  1.  [Install crane](https://github.com/google/go-containerregistry/tree/main/cmd/crane#installation)
```suggestion
1.  [Install crane](https://github.com/google/go-containerregistry/tree/main/cmd/crane#installation) for your system.
```

2024-08-20 19:19 UTC, jstirnaman commented on content/influxdb/clustered/install/configure-cluster/directly.md
>  You can obtain it with any standard OCI image inspection tool. For example:
```suggestion
You can obtain it with any standard OCI image inspection tool--for example:
```

2024-08-22 15:36 UTC, jenniferplusplus commented
@jstirnaman is there anything else I'm missing?

2024-08-22 21:35 UTC, jstirnaman approved these changes
LGTM! Thanks!

2024-08-27 14:58 UTC, merged