Add timezone support to v3 SQL docs
influxdata/docs-v2 pull request #5581
Opened 2024-08-28 21:29 UTC by sanderson

- Updates information about time zones in SQL across all v3 products
- Updates SQL data types documentation
- Adds missing time and date functions
- Adds information about how timezones change the behavior of some functions.

---

- [x] Rebased/mergeable

2024-08-29 14:29 UTC, jeffreyssmith2nd commented on content/influxdb/clustered/reference/sql/data-types.md
> +| TIMESTAMP     | Timestamp(Nanosecond, None)    | Nanosecond timestamp with a time zone offset |
Same comment as above

2024-08-29 14:29 UTC, jeffreyssmith2nd commented on content/influxdb/cloud-serverless/reference/sql/operators/other.md
> +{{< /expand-wrapper >}}
Same comment as below

2024-08-29 14:29 UTC, jeffreyssmith2nd commented on content/influxdb/cloud-serverless/reference/sql/data-types.md
> +| TIMESTAMP     | Timestamp(Nanosecond, None)    | Nanosecond timestamp with a time zone offset |
Same as above

2024-08-29 14:29 UTC, jeffreyssmith2nd commented on content/influxdb/cloud-dedicated/reference/sql/operators/other.md
> +{{< /expand-wrapper >}}
Same as below

2024-08-29 14:54 UTC, jstirnaman requested changes

2024-08-29 14:54 UTC, jstirnaman commented on content/influxdb/cloud-dedicated/reference/sql/data-types.md
> +Both SQL and Arrow data types play an important role is how data is operated on
```suggestion
Both SQL and Arrow data types play an important role in how data is operated on
```

2024-08-29 14:54 UTC, jstirnaman commented on content/influxdb/cloud-dedicated/reference/sql/functions/time-and-date.md
>  The `current_date()` return value is determined at query time and will return
```suggestion
The `current_date()` return value is determined at query time and returns
```

2024-08-29 14:54 UTC, jstirnaman commented on content/influxdb/cloud-dedicated/reference/sql/functions/time-and-date.md
> +For example, if you "bin" or "window" data into 15 minute intervals, an input timestamp of `2023-01-01T18:18:18Z` will be updated to the start time of the 15 minute bin it is in: `2023-01-01T18:15:00
```suggestion
For example, if you "bin" or "window" data into 15-minute intervals, an input timestamp of `2023-01-01T18:18:18Z` will be updated to the start time of the 15-minute bin it is in: `2023-01-01T18:15:00Z`.
```

2024-08-29 14:54 UTC, jstirnaman commented on content/influxdb/cloud-dedicated/reference/sql/functions/time-and-date.md
> +Strings are parsed as `YYYY-MM-DD` unless another format is specified. if no Chrono formats are provided.
Incomplete sentence.

2024-08-29 14:54 UTC, jstirnaman commented on content/influxdb/cloud-dedicated/reference/sql/functions/time-and-date.md
> +Strings are parsed as RFC3339nano timestamps if no
```suggestion
Strings are parsed as [RFC3339Nano timestamps](/influxdb/cloud-dedicated/reference/glossary/#rfc3339nano-timestamp) if no
```

2024-08-29 14:54 UTC, jstirnaman commented on content/influxdb/cloud-serverless/reference/sql/functions/time-and-date.md
>  The `current_date()` return value is determined at query time and will return
```suggestion
The `current_date()` return value is determined at query time and returns
```

2024-08-29 14:54 UTC, jstirnaman commented on content/influxdb/cloud-serverless/reference/sql/functions/time-and-date.md
> +Strings are parsed as `YYYY-MM-DD` unless another format is specified. if no Chrono formats are provided.
Incomplete sentence

2024-08-29 14:54 UTC, jstirnaman commented on content/influxdb/cloud-serverless/reference/sql/functions/time-and-date.md
> +Strings are parsed as RFC3339nano timestamps if no
```suggestion
Strings are parsed as [RFC3339Nano timestamps](/influxdb/cloud-serverless/reference/glossary/#rfc3339nano-timestamp) if no
```

2024-08-29 14:54 UTC, jstirnaman commented on content/influxdb/clustered/reference/sql/data-types.md
> +Both SQL and Arrow data types play an important role is how data is operated on
```suggestion
Both SQL and Arrow data types play an important role in how data is operated on
```

2024-08-29 14:54 UTC, jstirnaman commented on content/influxdb/clustered/reference/sql/functions/time-and-date.md
>  The `current_date()` return value is determined at query time and will return
```suggestion
The `current_date()` return value is determined at query time and returns
```

2024-08-29 14:54 UTC, jstirnaman commented on content/influxdb/clustered/reference/sql/functions/time-and-date.md
> +Strings are parsed as RFC3339nano timestamps if no
```suggestion
Strings are parsed as [RFC3339Nano timestamps](/influxdb/clustered/reference/glossary/#rfc3339nano-timestamp) if no
```

2024-08-29 14:54 UTC, jstirnaman commented on content/influxdb/clustered/reference/sql/functions/time-and-date.md
> +Strings are parsed as `YYYY-MM-DD` unless another format is specified. if no Chrono formats are provided.
Incomplete sentence

2024-08-29 21:01 UTC, jstirnaman approved these changes
LGTM. Maybe we need a note about the potential bug Jeff pointed out?

2024-08-29 21:05 UTC, sanderson commented
@jeffreyssmith2nd I know this is an upstream bug. Are we going to hold off pushing the TZ support out until this bug is fixed? When should these doc changes go live?

2024-08-29 21:06 UTC, jeffreyssmith2nd commented
> @jeffreyssmith2nd I know this is an upstream bug. Are we going to hold off pushing the TZ support out until this bug is fixed? When should these doc changes go live?

I don't know yet and am headed out for a long weekend. I'll check in with the team Tuesday on if we should delay or not.

Until then, I think we should hold the docs changes.

2024-08-29 21:08 UTC, jstirnaman requested changes

2024-08-29 21:08 UTC, jstirnaman commented on content/influxdb/cloud-serverless/reference/sql/functions/time-and-date.md
> +Strings are parsed as `YYYY-MM-DD` unless another format is specified. if no Chrono formats are provided.
> Incomplete sentence

> Strings are parsed as `YYYY-MM-DD` unless another format is specified. if no Chrono formats are provided.

?

2024-08-29 21:26 UTC, sanderson commented
@jstirnaman I think you may have been viewing the diff of an old commit. I went through and fixed all of those.

2024-08-29 21:47 UTC, jstirnaman approved these changes

2024-09-03 20:25 UTC, jeffreyssmith2nd commented
@sanderson Still on hold for the docs changes, waiting on some upstream discussion on if the `::timestamp` thing is actually a bug or if it is intended behavior. 

In the meantime, I'm removing all references to it in the docs where it isn't necessary to prevent any confusion for people down the line.

I will update the blog post and make a corresponding PR here as well once we know for sure what behavior we want out of `::timestamp`

2024-10-23 17:19 UTC, jeffreyssmith2nd commented
@sanderson This can be rolled out whenever you are ready, thanks for your help and patience with this one!

2024-10-30 22:42 UTC, merged