Issue #4047 - retention and bucket creation
influxdata/docs-v2 pull request #5675
Opened 2024-11-12 19:47 UTC by sleto-it

Fix for Issue #4047 for `/v2/` (better links between retention info and bucket creation info).

In addition, fixes also the following issues:

**1.** Wrong indentation

Issue 1.1 (before):
<img width="636" alt="issue1-before" src="https://github.com/user-attachments/assets/e722025b-f981-4cb7-944a-ebd9a1024b9a">

Issue 1.1 (**now**):
<img width="622" alt="issue1-now" src="https://github.com/user-attachments/assets/8726582b-c7fd-40bb-9117-288490e7963e">

Issue 1.2 (before):
<img width="599" alt="issue2-before" src="https://github.com/user-attachments/assets/9d8a368c-b17c-4b7f-a6cc-b229dcbefe44">

Issue 1.2 (**now**):
<img width="571" alt="issue2-now" src="https://github.com/user-attachments/assets/495d8118-5831-4169-848c-0a46070f6ff0">

**2.** Issue with bold

As it was before:
<img width="214" alt="issue3-before" src="https://github.com/user-attachments/assets/3c9f9c4f-830b-400f-8a19-7dcb55aad751">

As it is **now**:
<img width="211" alt="issue3-now" src="https://github.com/user-attachments/assets/4477a0a2-928c-45eb-8082-21e59f0ff57b">

**3.** Adds missing comma

---
_Describe your proposed changes here._

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Rebased/mergeable

2024-11-12 19:49 UTC, sleto-it commented
@jstirnaman FYI

2024-11-14 19:05 UTC, jstirnaman requested changes
Thanks again. Looks good--a few suggested changes.

2024-11-14 19:05 UTC, jstirnaman commented on content/influxdb/v2/reference/internals/data-retention.md
> +of time that a bucket retains data. Retention periods are set when [creating the buckets](/influxdb/v2/admin/buckets/create-bucket/),
```suggestion
of time that a bucket retains data.
You can specify the retention period when you [create](/influxdb/v2/admin/buckets/create-bucket/) or [update](/influxdb/v2/admin/buckets/update-bucket/) a bucket.
```

2024-11-14 19:05 UTC, jstirnaman commented on content/influxdb/v2/reference/internals/data-retention.md
> +and can be infinite or as short as an hour. [Points](/influxdb/v2/reference/glossary/#point)
```suggestion
Retention periods can be infinite or as short as an hour.
[Points](/influxdb/v2/reference/glossary/#point)
```

2024-11-14 21:04 UTC, jstirnaman approved these changes

2024-11-14 21:04 UTC, merged