Release notes for InfluxDB 2.7.11
influxdata/docs-v2 pull request #5686
Opened 2024-11-26 00:15 UTC by gunnaraasen

- Release notes for InfluxDB OSS 2.7.11.

- [x] Rebased/mergeable

2024-11-26 00:28 UTC, davidby-influx approved these changes
LGTM

2024-11-26 16:37 UTC, devanbenz approved these changes
LGTM

2024-11-27 15:05 UTC, jstirnaman approved these changes
LGTM. I'll create an issue to document the new options.

2024-11-27 15:05 UTC, jstirnaman commented on content/influxdb/v2/reference/release-notes/influxdb.md
> +- Add `--storage-wal-flush-on-shutdown` to flush WAL on database shutdown.
@jstirnaman New v2.7.11 options

2024-12-02 20:10 UTC, devanbenz requested changes

2024-12-02 20:10 UTC, devanbenz commented on content/influxdb/v2/reference/release-notes/influxdb.md
> +## v2.7.11 {date="2024-11-25"}
Please change date to today's date

2024-12-02 21:11 UTC, devanbenz approved these changes

2024-12-02 21:13 UTC, merged