WIP: Cloud v2 removal/ updates to Sign up page (5720)
influxdata/docs-v2 pull request #5726
Opened 2024-12-31 22:52 UTC by MeelahMe

Closes #

_Describe your proposed changes here._

- [ ] Signed the [InfluxData CLA](https://www.influxdata.com/legal/cla/)
  ([if necessary](https://github.com/influxdata/docs-v2/blob/master/CONTRIBUTING.md#sign-the-influxdata-cla))
- [ ] Rebased/mergeable

2024-12-31 23:34 UTC, jstirnaman commented
Just a tip: use `#5720` to [link the issue to your PR](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)--e.g. in your commit message, you can do `(closes #5720)`.

2025-01-01 00:13 UTC, jstirnaman requested changes
Looking good. There's more to this one than I originally realized. Let's wait for Scott's opinion.

2025-01-01 00:13 UTC, jstirnaman commented on content/influxdb/cloud/sign-up.md
> +- **V3**: Dedicated (multi-node or serverless)
```suggestion
```
Not a bad idea, but I don't think we want this kind of detail in this page.

2025-01-01 00:45 UTC, MeelahMe commented on content/influxdb/cloud/sign-up.md
> +### Other Deployment Options
made changes!

2025-01-01 00:45 UTC, MeelahMe commented on content/influxdb/cloud/sign-up.md
> +- **V3**: Dedicated (multi-node or serverless)
simplified details

2025-01-02 21:15 UTC, sanderson requested changes

2025-01-02 21:15 UTC, sanderson commented on content/influxdb/cloud/sign-up.md
> +**Note:** New InfluxDB Cloud signups are for version 3.0 only. If you are looking to use InfluxDB 2.0, consider self-hosting InfluxDB OSS 2.0.
I'd steer away from using "2.0" and "3.0". With the name change announced today for IOx-based products, I'm not sure how to handle older products. New products should be called "InfluxDB 3," but we've historically used "v1" and "v2" to avoid confusion with the actual semantic versioning.

```suggestion
> [!Note]
> #### New InfluxDB Cloud signups use InfluxDB 3
>
> New InfluxDB Cloud signups are for [InfluxDB Cloud Serverless, powered by the InfluxDB 3 storage engine](/influxdata/cloud-serverless/).
>
> If you are looking to use InfluxDB v2 (TSM), consider self-hosting [InfluxDB OSS v2](/influxdata/v2/).
```

2025-01-02 21:15 UTC, sanderson commented on content/influxdb/cloud/sign-up.md
> +- **InfluxDB Cloud (v3.0)**: Managed, multi-tenant or dedicated multi-node.
```suggestion
- **InfluxDB OSS v2 (single-node, self-hosted)**: Available for on-premises setups.
- **InfluxDB Cloud Serverless**: Managed, multi-tenant InfluxDB Cloud 3 instance.
- **InfluxDB Cloud Dedicated**: Managed, single-tenant InfluxDB Cloud 3 cluster.
```

2025-01-03 15:28 UTC, sanderson approved these changes

2025-01-03 16:06 UTC, jstirnaman approved these changes
One more naming fix and it's good to go! Good job!

2025-01-03 16:06 UTC, jstirnaman commented on content/influxdb/cloud/sign-up.md
```suggestion
{{< product-name >}} is API-compatible and functionally compatible with InfluxDB OSS v2.
The primary differences between InfluxDB OSS v2 and InfluxDB Cloud are:

```

2025-01-03 18:19 UTC, merged